### ISSUE TITLE
Ошибка в описании задания

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#1]
В ордынскую столицу ОРГРИММАР.
![wow 2017-07-06 16-28-14-088](https://user-images.githubusercontent.com/29949340/27911018-a391b02a-6268-11e7-97e5-cedfa3940cc8.jpg)

**Comment by Furnicarium** [comment]
алё, перечитай. "добраться до Оргриммара", чем не то же самое, что "Добраться до Москвы"? одно и то же
