### ISSUE TITLE
Бумаги Алого ордена

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#10]
Некорректно отображается текст.
![wow 2017-07-08 01-46-23-120](https://user-images.githubusercontent.com/29949340/27981574-e911e160-639e-11e7-90a4-2e31043dd32a.jpg)

**Comment by M2us** [comment]
Ошибка не является проблемой русификации игрового клиента или серверной локализации. Она связанна с использованием аддонов-переводчиков.
[Issue #16](https://github.com/WoWruRU/classicdb_ruRU/issues/16)
