### ISSUE TITLE
Джерард Румпель

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#100]
В оригинале его зовут Gerard Tiller
перевод на уровне Гордо
![4](https://user-images.githubusercontent.com/29949340/28099901-247d1f9c-66d0-11e7-9ff0-9e4f033e077f.jpg)
![wow 2017-07-12 02-16-57-117](https://user-images.githubusercontent.com/29949340/28099909-2f4988a2-66d0-11e7-8c38-00ce67f6bc42.jpg)

**Comment by Artur91425** [comment]
Вообще-то все норм. Имя Gerard по русски будет Джерард. Достаточно в гугл забить поиск "Джерард" и тебе выведут ссылки на известные личности в википедии, откуда можно посмотреть имя на изначальном языке. Везде пишут Gerard
