### ISSUE TITLE
Спрятанное сокровище капитана Сандерса, Ключи к сокровищу Сандера

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#101]
В оригинале текст подсказки и текст в задании совпадают, в то время как в русской версии переводили два разных человека. Оба перевода мне не нравятся, хотя я больше склоняюсь ко второму, из ключа. Короче, они должны быть одинаковыми, как в оригиналена англ.
"Очень хорошо, дружище! А теперь иди строго на восток. Обойди с востока утесы. Поищи разрушенную старую трубу на обочине. Там будет старый бочонок со следующей подсказкой". - из задания
а текст в ключа на скрине
![wow 2017-07-12 02-41-33-183](https://user-images.githubusercontent.com/29949340/28100104-358e0e1c-66d1-11e7-96b2-1c144a663ff8.jpg)

**Comment by FTNonsense** [comment]
Еще один ключ к сокровищу Сандерса
Вот в задании
"А отсюда иди на север. Иди прямо и прямо, никуда не сворачивай, пока не увидишь пустой кувшин рядом с одинокой мельницей на прибрежных скалах. Пошаришь там – может, и найдешь то, что ищешь".
снова ратую за перевод со скрина как основу, переводчик этих ключей был более правильным в своих переводах, просто прочтите оригинал и сравните
![wow 2017-07-12 02-41-44-899](https://user-images.githubusercontent.com/29949340/28100145-7bc2646e-66d1-11e7-9252-db3c1a9d3b28.jpg)

**Comment by FTNonsense** [comment]
Последний ключ к сокрвоищу Сандерса
"Раз уж ты нашел мой старый кувшин из-под виски, значит, ты близко подобрался к сокровищу! Иди от бутылки на запад и спустись к берегу. Доберешься до воды – не останавливайся! Плыви, пока не найдешь остров, где и находится мой сундук с сокровищем!"
а вот здесь нужно вставить в ключ перевод с задания, потому что судя по английскому, в ключе автор допустил очень много вольностей и потерял первоистичник. Здесь задание оказалось правильным переводом.
![wow 2017-07-12 07-13-11-150](https://user-images.githubusercontent.com/29949340/28100255-f1ad7a56-66d1-11e7-9592-fb9f53116976.jpg)

**Comment by M2us** [comment]
Ну, все вырезки представлены из заданий, которые сейчас на офе. Текущее описание квестов у нас чуть другое. Но я считаю, то, как сейчас представлено на официальном сервере полностью отражает весь смысл задания и никаких изменений не нужно. Так что, текст обновлен до официальной версии.
