### ISSUE TITLE
Эликсир страдания

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#103]
Никаких пауков-охотников нет, но есть "Лесной моховой ползун"
Поэтому следует поменять на *_"Лимфу моховых ползунов"_*
данная ошибка в переводе встречается часто, так как некоторые переводчики так переводили creeper, а в англ паук зовется "Forest Moss Creeper", как охотник, но это не всегда так,  у этого слова много значений и ползун было бы наиболее корректным. так что да, в задании надо менять.
![wow 2017-07-12 03-35-35-628](https://user-images.githubusercontent.com/29949340/28100473-540b9b32-66d3-11e7-8bff-ab7dd175d113.jpg)

**Comment by FTNonsense** [comment]
А, предмет тоже надо переименовать.
![wow 2017-07-12 03-44-33-949](https://user-images.githubusercontent.com/29949340/28100608-2cbcf390-66d4-11e7-8984-7572b708cbaf.jpg)

**Comment by FTNonsense** [comment]
повторно прочитав текст задания, обнаружил пару ошибок.
первая черта - неправильный перевод целого предложения, автор или хотел схалтурить работу, или не понял текста.
вот там:
" I've been conducting intense studies on possible killing agents to use in my concoctions but I haven't the time to collect them all."
мне лень объяснять ошибки, связанные с глаголами и временем, просто смотрите мой перевод и все поймете:
**_"Я проводил множественные исследования о различных смертоносных веществах, чтобы использовать их в своих составах, но у меня нет времени их собирать."_**
![wow 2017-08-05 16-41-39-168](https://user-images.githubusercontent.com/29949340/29004936-77156d8e-7ae1-11e7-8bbf-cd9ba72ccc26.jpg)
и да, не забудьте переименовать лимфу в предмете и в тексте, я все подчеркнул.

**Comment by FTNonsense** [comment]
![wow 2017-08-05 16-43-16-345](https://user-images.githubusercontent.com/29949340/29004941-93266884-7ae1-11e7-8b62-5250b885e7ac.jpg)

**Comment by FTNonsense** [comment]
вкладка "прогресс"
тут правиильнее не вещества, а "реагенты". ибо язык медведя.. ну какое это вещество?
![wow 2017-08-05 17-44-58-016](https://user-images.githubusercontent.com/29949340/29005267-56a832f0-7ae8-11e7-8e22-d55591955250.jpg)

**Comment by M2us** [comment]
Ну, там несколько видов пауков с которых добывается эта лимфа, но все они "моховой ползун".

Что касаемо предмета, дословно будет так; Лимфа ползуна.
Но, думаю что Лимфа паука-ползуна будет лучше. Уточнение никогда не помешает. )
