### ISSUE TITLE
Защита от магии льда

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#104]
Я бы сказал, что тут надо исправить "защиту от огня" на "защиту от магии льда", но, разобарвшись в английском интерфейсе, я понял, что это ошибка в ледяной магии!
На англе обе магии называются как:
Fire Ward
Frost Ward   - то есть лаконично, защита от чего-то.
Переводили два разных человека, в итоге должно быть "Защита от льда" у второго скрина.
![wow 2017-07-12 03-41-13-676](https://user-images.githubusercontent.com/29949340/28100543-c391fabe-66d3-11e7-81e6-5c643b2d0edd.jpg)
![wow 2017-07-12 03-41-14-859](https://user-images.githubusercontent.com/29949340/28100544-c3ae9624-66d3-11e7-83b6-335a94785ea9.jpg)

**Comment by M2us** [comment]
https://github.com/WoWruRU/classicdb_ruRU/issues/483
А лед все верно, от магии льда.
