### ISSUE TITLE
Аптекарь Лидон, эликсир страданий

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#105]
agents - вещества? Стоп, а как язык медведя может быть веществом? Короче, тут скорее реагенты, а лучше даже, по-русски, ингридиенты.
![wow 2017-07-12 03-44-33-949](https://user-images.githubusercontent.com/29949340/28100587-0d208b8c-66d4-11e7-8246-ba36b5bc7b62.jpg)

**Comment by FTNonsense** [comment]
А здесь надо бы исправить. В английском варианте больше конкретики:
"It will take but a moment for me to mix these components into what I have deemed an Elixir of Suffering."
здесь надо вместо "того" добавить "зелья"
"для создания зелья, что я хочу наречь эилксиром страданий"
И да, здесь либо оба слова с большой буквы, либо оба с маленькой. Так как это название определенного предмета, то оба надо с большой, как и в англ варианте
![wow 2017-07-12 03-45-01-447](https://user-images.githubusercontent.com/29949340/28100696-c746c49a-66d4-11e7-8bd7-690a69ebda72.jpg)

**Comment by M2us** [comment]
По первому скрину - https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0089_quest_elixir_of_suffering.sql#L5

**Comment by M2us** [comment]
Конкретика? Зелье?

Так-то он говорит вот о чем:

It will take but a moment for me to mix these components into what I have deemed an Elixir of Suffering.

Мне потребуется момент (мгновенье) чтобы смешать эти компоненты в то, что я хочу наречь эликсиром Страданий. 
То есть, как видим, если исправлять под конкретику, то слова зелье там нет. Речь о том, что он смешает те компоненты что мы ему принесли и он надеется получить эликсир, а не зелье.

И почему с маленькой, потому что это эликсир, а второе слово название, что с большой. Мы же не скажем: это Ручка Яблока. Нет, правильно будет: это ручка Яблока (Apple).    )))))
Конечно, сам итем написан с маленькой буквы, но везде с большой. Так что, итем будет переименован.

То есть, звучать будет так:
Мне понадобится совсем немного времени, чтобы смешать все эти компоненты и получить с них то, что я хочу наречь эликсиром Страдания.
