### ISSUE TITLE
Аругал

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#106]
Во-первых, в первой фразе обращение выделяется запятой. Еще и не переведена полностью, вот оригинал:
"I have changed my mind loyal servants, you do not need to bring the prisoner all the way to my study, I will deal with him here and now"
Надо допиливать к ней перевод. будет что-то типа:
**_"Я передумал, слуги мои, не нужно тащить пленника ко мне в кабинет, я сам разберусь с ним здесь и сейчас."_**

Во-вторых, вторая фраза тоже не допилена и тупо переведена, лишена смысла и ее надо заново полностью переводить нормально.
"You and your pathetic ilk will find no more success in routing my sons and I than those beggardly remnants of the Kirin Tor. "
что должно быть типа:
**_"Винсент! Ты и тебе подобные больше не будут вставать на моем пути, как и те жалкие остатки Крин-Тора."_** -  я пытался, не знаю даже, верно ли мысль уловил, да и "его детей" не смог вставить.

ОТ ТРЕТЬЕЙ ФРАЗЫ У МЕНЯ СУКА БОМБИТ, КТО ТАК ПЕРЕВЕЛ? Просто прочитайте третью фразу на скрине и оригинал. Переодчик тупой урод, просто тварь. тут надо все переделывать, полностью, ибо смысл весь абсолютно ПО-ТЕ-РЯН.
"If you will not serve my Master with your sword and knowledge of his enemies..."
должно быть что-то типо:
**_"Если ты не будешь служить моему учителю своим мечом и знанием его врагов..."_**
в ПОСЛЕДНЕЙ ФРАЗЕ ВСЕ БОЛЕЕ ИЛИ менее нормально, но вот вам оригинал:
"Your moldering remains will serve ME as a testament to what happens when one is foolish enough to trespass in my domain!""
и мой перевод:
**_"Твои трухлявые останки будут служить мне, как свидетельство того, как я поступаю с глупцами,  решившими посягнуть на мои владения!"_**
![wow 2017-07-12 04-59-58-497](https://user-images.githubusercontent.com/29949340/28100847-ba46fce6-66d5-11e7-917f-1983561273b8.jpg)

**Comment by M2us** [comment]
>Во-вторых, вторая фраза тоже не допилена и тупо переведена, лишена смысла и ее надо заново полностью переводить нормально.
"Vincent!  You and your pathetic ilk will find no more success in routing my sons and I than those beggardly remnants of the Kirin Tor."
что должно быть типа:
"Винсент! Ты и тебе подобные больше не будут вставать на моем пути, как и те жалкие остатки Крин-Тора." - я пытался, не знаю даже, верно ли мысль уловил, да и "его детей" не смог вставить.


Нет, чуть не верно. Здесь речь о том, что Винсент и ему подобные (и твой жалкий род, если быть точнее. Как мы знаем, по истории считается что именно Орда победила Аругала) не добьются большего успеха, как и те жалкие остатки Кирин-Тора (то есть, их успех явно не будет больше успеха Кирин-Тора), идя на его сыновей и его самого.

Примерно можно сделать вот так: Винсент! Тебе и твоим союзникам не следовало идти против меня и моих сыновей. Тебя постигнет та же участь, как и те жалкие остатки Кирин-Тора.
