### ISSUE TITLE
Интеллект I ступень

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#107]
lesser intellect - какая ступень еще?! Кроме того, больше ступеней не будет, только первая. подобный баг уже был, тупой перевод, а переводчик, что перевел так - даун.
Должно быть что-то вроде "Малый интелелкт", как и  с другими зельями, они там, маленькие, все "малыми зовутся"
![wow 2017-07-12 05-07-56-289](https://user-images.githubusercontent.com/29949340/28100913-2874e386-66d6-11e7-9117-50aa96a625d8.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/commit/f23211b7b9b6188282d6bc4e58af2dd5382e5133) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
