### ISSUE TITLE
Очень серьезная ошибка. Путаница Стражей смерти и ловчих смерти

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#109]
Давайте на чистоту, пока я искал ответы на прошлый репорт, то наткнулся на некую сменяемость их имен, и вот что выяснилось.
deathguard - страж смерти
deahstalker - ловчий смерти
Все это верно, но в вашей локали это все - одно и то же, что в корне НЕПРАВИЛЬНО И ТУПО. Исправлять нужно везде, на офе метелица уже фиксанула такую оплошность.
Вот вам первая жертва
![wow 2017-07-12 05-15-46-282](https://user-images.githubusercontent.com/29949340/28101068-25643da8-66d7-11e7-81f3-e2e080645a79.jpg)
![wow 2017-07-12 05-16-36-996](https://user-images.githubusercontent.com/29949340/28101069-257aaa7a-66d7-11e7-9ed9-a127b1a5c5d1.jpg)
тут надо менять название задания, текст в нем, если о них говорится как о стражах смерти, а также имена этих двух deathstalker'ов в Крепости Темного Клыка. Остальных ищите сами по своей базе, но я помню, что видел много таких по ходу игру, неверно переведенных в "Стражей смерти",
![wow 2017-07-12 05-15-46-282](https://user-images.githubusercontent.com/29949340/28101105-59f19d18-66d7-11e7-9bca-f6310903a2d2.jpg)
![wow 2017-07-12 05-16-36-996](https://user-images.githubusercontent.com/29949340/28101107-5a102ee0-66d7-11e7-8ece-aae87eca5890.jpg)

**Comment by FTNonsense** [comment]
З.Ы.:
Готовясь к нападению на крепость Темного Клыка, мы отправили на разведку двух ловчих смерти. Они не возвращаются вот уже много дней, но без их отчета нам не организовать успешного нападения!

Итак, вот твое задание, <имя>. Отправляйся в крепость Темного Клыка на юге и найди ловчих смерти Адаманта и Винсента. Найди их и помоги им, если сможешь.

Это очень опасное и важное задание, <имя>. Не подведи нас.

**Comment by FTNonsense** [comment]
![wow 2017-07-12 05-17-30-543](https://user-images.githubusercontent.com/29949340/28101160-a5d321ca-66d7-11e7-94e1-1f0462277a43.jpg)
Его зовут не Эрланд Винсент, а просто Винсент, фикс.

**Comment by FTNonsense** [comment]
вот еще
![wow 2017-07-28 22-31-40-074](https://user-images.githubusercontent.com/29949340/28744455-3b6a9c70-7472-11e7-9a5a-031df36e6f9b.jpg)

**Comment by FTNonsense** [comment]
![wow 2017-07-29 19-32-20-180](https://user-images.githubusercontent.com/29949340/28753716-596571be-7549-11e7-8a48-f3757ec20410.jpg)

**Comment by FTNonsense** [comment]
и имя его
![wow 2017-07-29 19-32-55-195](https://user-images.githubusercontent.com/29949340/28753717-7499ff40-7549-11e7-9a98-baeca83891d0.jpg)

**Comment by FTNonsense** [comment]
![s](https://user-images.githubusercontent.com/29949340/28775720-89558e3e-7604-11e7-9eaf-5c2a713e86d2.jpg)
еще здесь, и при отслеживании задания тоже. в оригинале там все "deathstalker"

**Comment by FTNonsense** [comment]
вот еще здесь, где написано "стражи смерти" - в оригинале "deathstalkers" т.е **_"ловчие смерти"_**
![wow 2017-08-05 19-26-22-781](https://user-images.githubusercontent.com/29949340/29006443-fd1cf2fc-7b00-11e7-9d19-fdd7c71d5a7e.jpg)
P.s: заодно исправьте "люди из Хилсбрада" на "**_жители Хилсбрада_**", чтобы дать понять, что мы говорим о жителях той деревни, а не локациии в целом.
и еще, там ловчего зовут не "Томм", а "**_Том_**", тоже исправьте.

**Comment by FTNonsense** [comment]
p.p.s: иисправьте еще, не горожанина "Уилка", а "**_Горожанина Вилкса"_**
![wow 2017-08-05 19-27-26-944](https://user-images.githubusercontent.com/29949340/29006458-52b77840-7b01-11e7-80fe-2c27b50c0b33.jpg)

**Comment by M2us** [comment]
>вот еще здесь, где написано "стражи смерти" - в оригинале "deathstalkers" т.е "ловчие смерти"
Разыскивается за убийство стража смерти Томма.

В данном случае верно, потому что там Deathguard, а не Deathstalker:

А вот Фрая, да, там не страж смерти, а ловчий смерти.


>P.s: заодно исправьте "люди из Хилсбрада" на "жители Хилсбрада",

Там говорится именно о людях, ведь humans. Это как уточнение, что ни дворфы, ни ночные эльфы, а именно люди.
