### ISSUE TITLE
Приказы Севрена

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#11]
Опечатки или не знаю что, в общем лишние $G в тексте.
![wow 2017-07-08 04-31-14-644](https://user-images.githubusercontent.com/29949340/27981587-266bc896-639f-11e7-8b43-6785fedfc71a.jpg)

**Comment by FTNonsense** [comment]
А еще текст неверно отображается, слишком много абзацев и за рамки заходт.

**Comment by M2us** [comment]
Ошибка не является проблемой русификации игрового клиента или серверной локализации. Она связанна с использованием аддонов-переводчиков.
[Issue #16](https://github.com/WoWruRU/classicdb_ruRU/issues/16)
