### ISSUE TITLE
Блуждающие духи - "Блуждающие души"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#110]
Во-первых, все призраки женского пола, поэтому я настаиваю, чтобы их из "духов" переименовали в "души". Подобный опыт есть с рарным мобов в Тирисфальских лесах, где как раз есть "Блуждающая душа", которую я убивал, с такой же моделькой, кстати.
Затем, у заклинания на скрин енеправильный перевод, полный отсебятины, вот оригинал:
"Cursed to periodically summon malevolent ghosts."
из-за тупого описания я долго не мог понять, что делает этот дебаф..
Короче, надо переименовывать НИПов и править тут описание.
![wow 2017-07-12 05-17-09-677](https://user-images.githubusercontent.com/29949340/28101215-1503a7b8-66d8-11e7-8664-86ff5525eb26.jpg)
![wow 2017-07-12 05-17-09-677](https://user-images.githubusercontent.com/29949340/28101225-28f4426e-66d8-11e7-967c-62c9386c524d.jpg)
![wow 2017-07-12 05-33-41-073](https://user-images.githubusercontent.com/29949340/28101226-28fb1ff8-66d8-11e7-9065-3a5b86762416.jpg)

**Comment by M2us** [comment]
Имена НПС как и название способности переведено правильно.
Haunting Spirits - Блуждающие духи.
Haunting Spirit - Блуждающий дух.

Было бы там soul, то другое дело. Мы же не переводим способность: Your spirit как, ваша душа..., всегда это означало Дух. Look! This is evil spirit - как переводят? Верно, смотри! Это злой дух!
Вот как пример.
http://www.wowhead.com/spell=138483


>Затем, у заклинания на скрин енеправильный перевод, полный отсебятины, вот оригинал:
"Cursed to periodically summon malevolent ghosts."

Даже не знаю откуда было взято это описание. То что на скрине, на англ. звучит как: Haunted...

Описание скила, который игрок не видит, но может чекнуть на различных базах данных, звучит как:
Curses an enemy for $d., causing it to be periodically haunted by malevolent ghosts.
Что в переводе: Противника в течение $d. периодически преследуют злобные призраки.
