### ISSUE TITLE
Страж Подгорода, учитель Алхимии

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#111]
Эм.. Что? можно мне англ текст? даже без него, я вижу что это какой-то треш, а не перевод, но надо убедиться. Все равно как баг, тут как минимум опечатка.
З.Ы.: я знаю, что текст стилизован под "плохо говорящих" поганищ нежити, но тут совсем логики все лишено.
![wow 2017-07-12 06-21-35-391](https://user-images.githubusercontent.com/29949340/28101412-5e119aae-66d9-11e7-953d-40ebef1f2fd6.jpg)
Чего только стоит Район фармацевтов, переведенный.. эм.. это вообще перевод?

**Comment by M2us** [comment]
Да, тест отсюда, но переведен он чуток неверно. Данный НПС сообщает игроку что он заглянул в район фармацевтов.
