### ISSUE TITLE
Вооружены и очень опасны!

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#113]
Ошибка, его зовут Вилкс.
![wow 2017-07-12 08-25-43-525](https://user-images.githubusercontent.com/29949340/28102086-070c6496-66de-11e7-9cb0-34fff88d938d.jpg)

**Comment by M2us** [comment]
[Исправлено](https://github.com/WoWruRU/classicdb_ruRU/commit/030ef7d13a55c1c98164c1d5a9a894668537be3e#diff-cb9c35a4490f503c8d7c9ede005c6a17R41).
