### ISSUE TITLE
Подводные дыхание

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#114]
Не до 300%, а на "300% длиннее обычного."
англ:
Underwater breath lasts 300% longer than normal.
![wow 2017-07-12 08-55-05-710](https://user-images.githubusercontent.com/29949340/28119904-7a2f300e-6727-11e7-8962-bcd616c22209.jpg)

**Comment by M2us** [comment]
[Изменения ](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0059_loc_spell_racial_bonus.sql)будут приняты в следующем обновлении после 28.09.2017.
