### ISSUE TITLE
Пронзенная броня

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#115]
Надо бы поправить описание, на более корректное и правильное.
Метелица уже тоже его поправила у себя.
на:
"Показатель брони снижен на 50%."
![wow 2017-07-12 09-30-55-592](https://user-images.githubusercontent.com/29949340/28120676-c3f29b8e-6729-11e7-8098-f3e2b5fcc3dd.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0010_loc_spell_pierce_armor.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
