### ISSUE TITLE
Разъяренный - "Разъяренный Стенли"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#119]
НИП номер 2275
В английском варианте "Enraged Stanley", а в русском просто "Разъяренный"
Вообще, я бы перевел это как "Взбешенный" или типо того, ведь собачку не разозлили какими-то действиями, а сделали такой под действиям зелья агонии. То есть как-бы искусственно "взбесили"
![wow 2017-07-12 11-06-15-800](https://user-images.githubusercontent.com/29949340/28124830-d75eeac2-6735-11e7-8c18-5fa966fe9d5a.jpg)

**Comment by M2us** [comment]
У всех существ приставка Enraged переведена как Разъяренный. Да и не так-то уж плохо, собачка разъяренная. А вот то что она Стэнли, нужно дописать.
