### ISSUE TITLE
Охота за яйцами, вспарывающий коготь и все что с этим связано

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#121]
Во-первых, силитидов много и должно быть "Курган силитидов" у объекта.
![ss](https://user-images.githubusercontent.com/29949340/28132200-29f4d6d6-674d-11e7-9792-914a38e689fc.jpg)
![sss](https://user-images.githubusercontent.com/29949340/28132197-298c86f8-674d-11e7-8ce5-6e1728736de3.jpg)
Во-вторых, "digging claw" - не "вспарывающий коготь" - с каких пор "to dig" - это "вспороть"? Даже в опсиании к предмету написан правильный перевод "выкапывание яиц".
Так что должно быть "Выкапывающий коготь" или в этом духе. 
![wow 2017-07-12 18-30-28-562](https://user-images.githubusercontent.com/29949340/28132259-5898b58e-674d-11e7-8788-1a09da0db736.jpg)
Заклинание "урожай яиц силитидов" что в оригинале "Harvest Silithid Egg" - тупой перевод из трех несвязанных слов. Должно быть что-то вроде "Сбор яиц силитидов", а правильнее по аналогии к описание предмета, будет связь и логика - "Выкапывание яиц силитидов"
![wow 2017-07-12 18-37-52-819](https://user-images.githubusercontent.com/29949340/28132346-a18eded0-674d-11e7-8f23-acc0785adedc.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0012_loc_spell_harvest_silithid_egg.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
