### ISSUE TITLE
Мор'рогал и ущелье камнепадов + Цунаман

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#122]
Так уж повелось, что "Stonetalon Mountains" перевели как "Когтистые горы", хотя можно было бы вполне перевести как "Горы Каменного Когтя", что неправильно, конечно, в рамках локализации.
Так вот, переводчики заданий и все прочего, английское сокращение "Stonetalon" без "mountain"s так и перевели - Каменный Коготь, а потому все задания и НИПы живут как-бы в другой локации с неправильным переводом. В русском "mountains" убрать нельзя, поэтому следует дописывать
пр. с первого скрина:
"В Когтистых Горах есть множество пещер"....
![wow 2017-07-12 22-28-04-555](https://user-images.githubusercontent.com/29949340/28165905-deddcd5c-67e6-11e7-9c77-88b4569209c2.jpg)
![wow 2017-07-12 22-28-48-014](https://user-images.githubusercontent.com/29949340/28165918-f201e4c2-67e6-11e7-9f48-e20e57db56cb.jpg)

**Comment by FTNonsense** [comment]
Цунаман, Война элементалей
Та же ошибка с "Когтистыми горами" - "горами Каменного когтя"
Плюс, в рамках дальнейшей локализации, метелица перевела "Нептулона" как:
"Нептулон Хозяин Приливов", что намного убедительнее звучит на русском, учитывая, что он верховный элементаль воды.
![wow 2017-07-12 22-29-08-912](https://user-images.githubusercontent.com/29949340/28166127-cbd54b12-67e7-11e7-9a76-190b0b68ed53.jpg)

**Comment by M2us** [comment]
Есть и подлокации Каменный Коготь и т.п.
https://vignette.wikia.nocookie.net/wow/images/7/7f/WorldMap-StonetalonMountains.jpg/revision/latest?cb=20120128090954&path-prefix=ru

Даже на вовики упоминается Каменный Коготь.

Да и в англ. также, есть понятие как Stonetalon - Каменный Коготь, когда говорят о какой-то местности, а есть название локации - Stonetalon Mountains, что не иначе можно перевести как: Когтистые горы.


А вот Нептулон, да, стоит исправить.
