### ISSUE TITLE
Дже'неу Санкри, среди руин

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#123]
Маленький баг. Стихии должны быть с маленькой буквы - см. англ, плюс, я все же считаю, что там должны быть не "стихии", а **"элементали"** или **"духи стихий"**. Там речь говорится не о стихиях как о явлении, а о вполне себе разумных существах, с которым шаманы Служителей Земли контактируют
![wow 2017-07-12 22-51-06-056](https://user-images.githubusercontent.com/29949340/28166358-a1b8bf3e-67e8-11e7-9793-712197fd729b.jpg)

**Comment by M2us** [comment]
elements - Стихии (а как иначе перевести на англ. слово Стихии?). Поэтому и с большой, что уточнение, что это не те обычные стихии которые понимаем мы. Всегда так было...
