### ISSUE TITLE
Отсыревшая записка, верность Древним Богам

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#126]
Здесь вроде переведено верно, но тавтология...
вот англ:
"The water elemental spirits are strong within them and they will aid our aquamancers greatly in their own summonings."
я бы переделал что-то вроде "в них сосредоточена могучая сила элементалей воды..." и дальше как было. СМысл не теряется.
![wow 2017-07-12 23-08-46-986](https://user-images.githubusercontent.com/29949340/28167152-aa7e8ff6-67eb-11e7-9657-aa9fb90737db.jpg)

**Comment by M2us** [comment]
А как же духи? Там говорится что в них находятся сильные духи элементалей воды.
The water elemental spirits are strong within them

И вот так теряется смысл, что вроде просто сила элементалей воды. Но нет, там именно духи. Так что, все верно.
