### ISSUE TITLE
Жрица прилива из Непроглядной Пучины

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#127]
Проанализировав всех НИПов в этой локации и у ее входа, я пришел к выводу, что "из" здесь лишнее. Нет, это не неправильный перевод, но у всех остальных наг вокруг нет этого предлога, они просто "Мирмидон Непроглядной Пучины", а здесь надо придерживаться точности. Поэтому надо исправить.
![s](https://user-images.githubusercontent.com/29949340/28167288-2168c24e-67ec-11e7-9e99-a965df22f544.jpg)
![ss](https://user-images.githubusercontent.com/29949340/28167287-21638fe0-67ec-11e7-9bab-10096a484bbc.jpg)
![wow 2017-07-12 23-21-13-893](https://user-images.githubusercontent.com/29949340/28167307-3886f5c2-67ec-11e7-970a-11e77471105b.jpg)
![wow 2017-07-12 23-27-57-790](https://user-images.githubusercontent.com/29949340/28167308-388a643c-67ec-11e7-9170-cd15bdae088b.jpg)

**Comment by FTNonsense** [comment]
![wow 2017-07-12 23-29-57-999](https://user-images.githubusercontent.com/29949340/28167375-8547fbf4-67ec-11e7-9a3c-a30b947c4536.jpg)

**Comment by FTNonsense** [comment]
или все таки "из" надо? тут вопрос все же локализации. Хмм, решайте сами, я только зарепорчу.

**Comment by FTNonsense** [comment]
может все таки надо "из".. не знаю.
![wow 2017-08-08 22-18-42-157](https://user-images.githubusercontent.com/29949340/29125963-27ee3b42-7d2e-11e7-8773-5f8bb5d2afea.jpg)
![wow 2017-08-08 22-20-56-886](https://user-images.githubusercontent.com/29949340/29125962-27ed563c-7d2e-11e7-9f31-24f36db6231b.jpg)

**Comment by FTNonsense** [comment]
![wow 2017-08-08 22-34-59-025](https://user-images.githubusercontent.com/29949340/29125992-40b41354-7d2e-11e7-9e48-5121b7eacd1a.jpg)

**Comment by M2us** [comment]
Пойдем на поводу у массы. Только у 1 существа из всех таких есть ИЗ, так что, сделаем его как и всех других.
