### ISSUE TITLE
Леди Саревесс

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#128]
Неправильный перевод скриптовой речи.
Должно быть: "Вам здесь не место! Убить их!" - по аналогии с озвучкой, как у всех нормально-переведенных боссов
![wow 2017-07-12 23-33-00-374](https://user-images.githubusercontent.com/29949340/28167427-afd4c9ce-67ec-11e7-921f-5d2d8f54cc0d.jpg)

**Comment by M2us** [comment]
Так-то текстовый перевод более правильный, ведь вот оригинал.
You should not be here! Slay them! - Вас не должно быть здесь! Убейте их!

Но озвучили как - Вам здесь не место! Убить их!
