### ISSUE TITLE
Благословение Черных Глубин - "Благословение Непроглядной Пучины"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#129]
Неправильный перевод, да и добавить нечего, проосто смотрите английский вариант.
![wow 2017-07-12 23-49-28-120](https://user-images.githubusercontent.com/29949340/28167791-e467e1a2-67ed-11e7-905e-3c4384227f65.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0013_loc_spell_blessing_of_blackfathom.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
