### ISSUE TITLE
Старина Серракис - "Старина Серра'кис'

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#130]
неправильный перевод, смотрите англ вариант, надо исправлять.
![s](https://user-images.githubusercontent.com/29949340/28168142-2fbcb67c-67ef-11e7-9316-ad63ede45aa0.jpg)
![wow 2017-07-13 00-10-58-717](https://user-images.githubusercontent.com/29949340/28168141-2fbc71a8-67ef-11e7-9434-bbd20eaec6ff.jpg)

**Comment by FTNonsense** [comment]
и со связанным с ним предметом так же.
![wow 2017-08-11 23-26-14-141](https://user-images.githubusercontent.com/29949340/29241777-2b53e9ac-7f91-11e7-9709-1a2170a2d75f.jpg)

**Comment by FTNonsense** [comment]
и еще один
![wow 2017-08-14 23-41-22-738](https://user-images.githubusercontent.com/29949340/29315766-ffb0b8ce-81d5-11e7-9aef-34c7f1cba808.jpg)

**Comment by M2us** [comment]
Глупость, не всегда сохраняется '
Даже если его имя вбить через различные переводчики имен и т.п., все равно будет Серракис.

Пример из след. репорта: He is located at the Horde's. Мы же не перенес это '.
