### ISSUE TITLE
Дже'неу Санкри, Барон Акванис

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#131]
Первая линия - не хватает слова "Пучине"
Вторая, я считаю, что для литературности в русском языке, да и по лору, подчеркнутое надо переделать в "давно считается оскверненным элементалем" - ведь Акванис элементаль воды. А сила стихий..Скажем так, в лоре варкрафта стихия и элементаль - разные вещи.
![wow 2017-07-13 00-43-54-928](https://user-images.githubusercontent.com/29949340/28168535-76592736-67f0-11e7-8dc3-717f9b8155f0.jpg)

**Comment by M2us** [comment]
> Первая линия - не хватает слова "Пучине"

Пропущено слово "Пучине", потому что персонаж ее так называет. Даже на английском: in Blackfathom, you say?

А инст называется: Blackfathom Deeps


>ведь Акванис элементаль воды. А сила стихий..Скажем так, в лоре варкрафта стихия и элементаль - разные вещи.

Да, он элементаль воды, но его называют corrupted elemental power. Он - оскверненная сила стихии (не стихий), другими словами, он является оскверненной силой воды, ведь он элементаль воды. Все верно переведено. Было бы там слово стихий, другое дело, ошибка. А так он сила своей стихии.
