### ISSUE TITLE
Любой хозяин таверны, описание подземелья Тюрьма

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#133]
Первое - "в стране" надо убрать, так как описание доступно и оркам, а они не живут "в стране" Альянса, скорее "самых опасных преступников здешних земель"
Более того, вот оригинал текста:
The Stockade is a high-security prison complex, hidden beneath the canal district of Stormwind city. Presided over by Warden Thelwater, the Stockade is home to petty crooks, political insurgents, murderers and a score of the most dangerous criminals in the land. Recently, a prisoner-led revolt has resulted in a state of pandemonium within the stockade - where the guards have been driven out and the convicts roam free. **Warden Thelwater has managed to escape the holding area and is currently enlisting brave thrill-seekers to venture into the prison and kill the uprising's mastermind - the cunning felon, Bazil Thredd.**
Начиная с выделенного жирным текстом - перевода нет, надо доделать и исправить.
![wow 2017-07-13 01-02-40-055](https://user-images.githubusercontent.com/29949340/28169022-1455b2c8-67f2-11e7-954e-f0e233ab648e.jpg)

**Comment by M2us** [comment]
[Закрыто.](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0109_npc_text_stockade%20.sql)
