### ISSUE TITLE
Тюремщики Малгрен и  Этон

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#137]
Переводчики наверное не знали, но слово "web" переводится не только как "паутина", а еще как ### "сеть" - на что и надо исправитьн азвание этой способности, бездарно промтоведенный даунами.
![wow 2017-07-13 18-30-00-519](https://user-images.githubusercontent.com/29949340/28175824-5fe09870-6806-11e7-91a8-236486fa2490.jpg)

**Comment by M2us** [comment]
Дополню: способность называется не web, а net.

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0014_loc_spell_net.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
