### ISSUE TITLE
Регистрационная книга Хилсбрада

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#140]
Не Лазурного рудника, а Лазуритового. Разница огромная.
![wow 2017-07-13 20-57-57-900](https://user-images.githubusercontent.com/29949340/28181365-664cda30-6819-11e7-9a94-fbf3e02cc7d7.jpg)

**Comment by FTNonsense** [comment]
![wow 2017-07-13 21-02-12-289](https://user-images.githubusercontent.com/29949340/28181372-7211e1b2-6819-11e7-96e5-dcaf79f4c280.jpg)

**Comment by Artur91425** [comment]
то, что текст выезжает, это опять баг в аддоне. Я поправил.
