### ISSUE TITLE
Название баффа, Сила I ступень

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#15]
Очень странный перевод баффа, учитывая, что в английском варианте это Lesser Strength и никаких ступеней нет. Считаю, что это надо исправить, при чем у всех баффов, если подобное еще встретится.
![wow 2017-07-08 23-51-40-704](https://user-images.githubusercontent.com/29949340/27990048-828527d2-645b-11e7-80d1-d8d5b32fe362.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/commit/f23211b7b9b6188282d6bc4e58af2dd5382e5133) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
