### ISSUE TITLE
Страж смерти Диллинджер, разговор с Диллинджером

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#153]
Первая черточка - одна точка лишняя.
Вторая черточка - точки не хватает, чтобы было многоточие.
пруф:
"You're here for a mission? Good. I have an important one, and one that will test your skill in combat..."
![wow 2017-07-15 00-37-03-148](https://user-images.githubusercontent.com/29949340/28232076-e76efd3c-68ff-11e7-9b87-339ca710307f.jpg)

**Comment by M2us** [comment]
Ранее было исправлено.
