### ISSUE TITLE
Страж смерти Диллинджер, Улаг Колун

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#154]
Во-первых, подчеркнутое предложение явное преувеличение. Отрекшиеся не обладают религиозному верованиями в реинкаранции, учитывая, что они сами по сути "воскресились" и вообще, этого нет в оригинале текста:
"Now, finally, it is time to free him. " требую заменить ту ошибку на что-то вроде: "Теперь, наконец, настало время освободить его".
![wow 2017-07-15 00-37-40-178](https://user-images.githubusercontent.com/29949340/28232288-f1e0a2d8-6900-11e7-9c1e-b01d9cd597d8.jpg)

Затем, помимо этого, с каких пор "level" у переключателя переводится как "пусковой механизм" 0_о - там что, какая-то сложная система по запуску? Нет же, там только магические чары, поэтому это, как мне кажется, следует переименовать.
![wow 2017-07-15 00-38-31-092](https://user-images.githubusercontent.com/29949340/28232293-fff15f66-6900-11e7-80d6-a55ebe25c6c3.jpg)
ид кнопки: 104593

**Comment by FTNonsense** [comment]
З.Ы.: так ответ дан же в самом задании! Переименуйте в "переключатель мавзолеяя". Идеально.

**Comment by FTNonsense** [comment]
Это же задание, вкладка "прогресс"
чисто технический баг, заменяется более нейтральной фразой, исходя с оригинала
"Your task is yet undone, <name>. It is not wise for a <class> to show fear..."
типо:
"<класс>, для таких как ты неразумно проявлять страх..."
![wow 2017-07-15 00-40-13-103](https://user-images.githubusercontent.com/29949340/28232377-6c0fef78-6901-11e7-9ec7-8e8e520a439f.jpg)

**Comment by M2us** [comment]
Ранее было исправлено.
