### ISSUE TITLE
Письмо Тармена, текст

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#16]
Текст заходит за рамки, слишком много абзацев или типо того.
![wow 2017-07-09 01-06-04-915](https://user-images.githubusercontent.com/29949340/27990053-acfb48b6-645b-11e7-954c-7b7e86dc7fb9.jpg)

**Comment by Artur91425** [comment]
Это проблема аддона переводчика. К серверной локализации отношения не имеет.
