### ISSUE TITLE
Ружейник Дун Гарока - "Стрелок Дун Гарока"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#161]
еще в старом добром warcraft 3 rifleman переводили как "стрелок" - что довольно правильно и точно отражало суть этих юнитов-дворфов.
И раз уж в игре много отсылок к вк3, то для корректного перевода переименовать архаичный "ружейник" на "стрелка" надо.
![wow 2017-07-15 23-08-20-062](https://user-images.githubusercontent.com/29949340/28242551-f4e3b622-69bf-11e7-8ea0-7cd70dfc7a6e.jpg)
ид 2345

**Comment by FTNonsense** [comment]
![wow 2017-08-13 17-11-22-678](https://user-images.githubusercontent.com/29949340/29254124-75037ef0-809f-11e7-9755-41528e0a689d.jpg)
ДАЖЕ в задании

**Comment by M2us** [comment]
У близзов все также. А с новой политикой русика (что все аддоны будут писаться под оф.), данная русификация также будет следовать переводу от близзард.
