### ISSUE TITLE
Исцеляющий поток

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#162]
Мелочь, но должно быть "на 6 ед." тогда уж, а вообще, пересмотрите все опсиания и бафы скилов, так много тупости.
![wow 2017-07-15 23-24-18-311](https://user-images.githubusercontent.com/29949340/28242589-dd2129ce-69c0-11e7-8ae4-2361cf49f27f.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0015_loc_spell_healing_stream.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
