### ISSUE TITLE
Ящик с отверстиями

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#165]
Промт-перевод, метелица уже все исправила.
Должно быть:
**"Использование: Откройте в лабиринтах Иглошкурых, в том месте, где растут клубни, и выпустите шмыгуноса."**
![wow 2017-07-16 17-43-14-928](https://user-images.githubusercontent.com/29949340/28249624-36bc9906-6a6a-11e7-950e-ce94907ad113.jpg)

**Comment by M2us** [comment]
[Изменения ](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0064_loc_spell_summon_snufflenose.sql)будут приняты в следующем обновлении после 28.09.2017.
