### ISSUE TITLE
Недоставленное письмо, текст задания

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#17]
Везде действия персонажей обозначаются либо треугольными скобками, либо звездочками. Смотрите английский вариант, тут короч ошибка.
![wow 2017-07-09 01-41-39-521](https://user-images.githubusercontent.com/29949340/27990055-e0ea694a-645b-11e7-94f2-2f59e71a7f90.jpg)

**Comment by M2us** [comment]
[0008](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0008_update_8.sql#L380)
Исправлено.
