### ISSUE TITLE
Властитель Таранный Клык, Лабиринты Иглошкурых

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#170]
Я продолжаю требовать фикса скриптовых речей, которые должны совпадать с озвучкой, как в английском варианте. Более того, текстовый вариант фразы и вовсе неправильный.
"За Агамагган!" - в смысле? Это их бог, значит Агамагган"а" - автор даже не знал что это, что уж говорить о рассинхроне. Разумеется, у студией дубляжа переводчики более профессиональные и они должны озвучить правильно - и так и есть.
КОРОЧЕ, ДОЛЖНО БЫТЬ ТАК - "Агамагган победит!"
![wow 2017-07-16 23-42-25-798](https://user-images.githubusercontent.com/29949340/28251437-0f7221ee-6a8e-11e7-9882-c51b448e1d78.jpg)
за пруфами вот вам скриншот фраз финального босса инста. все ее реплики 100% совпадают с озвучкой и они - ### ПРАВИЛЬНЫЕ
![wow 2017-07-16 23-56-24-921](https://user-images.githubusercontent.com/29949340/28251441-2072d5ba-6a8e-11e7-84a9-f30c52fcdfaa.jpg)

**Comment by M2us** [comment]
Так-то: For Victory! For Agamaggan!

И более правильный текстовый вариант, просто не хватает буквы "а".

Но, хорошо, сделаем как у озвучки. )
