### ISSUE TITLE
Мысленная дрожь

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#171]
на офе пофиксено.
должно быть:

"Скорость произнесения заклинаний снижена на 20%."

![wow 2017-07-16 23-47-43-165](https://user-images.githubusercontent.com/29949340/28251838-f89a7878-6a96-11e7-874f-93960bdcc94a.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/commit/55d4a30512e1556478aebed13de86620db36ecfa) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
