### ISSUE TITLE
Голова посланника Малкина - "голова посла Малкина"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#173]
Посол и посланник - абсолютно разные вещи, просто почитайте про политические ранги в посольствах, да даже элементарный словарь скажет это.
Скрина не сделал, это сразу на будущее.
ид предмета: 17009

**Comment by M2us** [comment]
Закрыто.
[0013](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0013_item_ambassador_malcin's_head.sql)
