### ISSUE TITLE
Грохот, да и все заклинания по такому типу

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#182]
в общем-то, на офе везде "прмиенять" заменили на "произносить" - что более правильно, поэтому и вам советую тогда переписать все описания к этим скилам, как вы переписывали таланты.
![wow 2017-07-18 14-32-46-054](https://user-images.githubusercontent.com/29949340/28330223-d18be5b0-6bfd-11e7-94ab-6b9b5598ee02.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0017_loc_spell_sonic_burst.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
