### ISSUE TITLE
Тролли пера

### ISSUE THREAD

**Issue by Artur91425** [WoWruRU/classicdb_ruRU#184]
![bandicam 2017-07-19 13-35-21-462](https://user-images.githubusercontent.com/24303693/28363095-c75daefe-6c87-11e7-8076-0a1cce3e6f73.jpg)
Оригинал:
![bandicam 2017-07-19 13-37-21-121](https://user-images.githubusercontent.com/24303693/28363103-cffa9176-6c87-11e7-937b-a737ac69d781.jpg)

Описание цели квеста надо поправить, думаю на такой вариант:
"Принесите 6 перьев вуду из троллей в затонувшем храме."
Ну и соответственно названия предметов поправить на:
"... перо вуду"

**Comment by M2us** [comment]
У близзов до сих пор так. )
