### ISSUE TITLE
Шаровидный кровавый камень

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#186]
Ну там все остальные с большой буквы, поэтому либо "Кровавый" здесь с большой, либо у всех остальных с маленькой

![wow 2017-07-20 22-06-01-562](https://user-images.githubusercontent.com/29949340/28434376-1a80b0d6-6da0-11e7-9b9d-e28c8f0c7d77.jpg)

**Comment by Artur91425** [comment]
Лучше у всех строчные буквы писать.
