### ISSUE TITLE
Wrath of Cenarius

### ISSUE THREAD

**Issue by Artur91425** [WoWruRU/classicdb_ruRU#192]
"При успешной атаке вашим боевым заклинанием вы получаете шанс увеличить урон ото всех заклинаний и эффектов на 132 ед. на 10 сек."

Предлагаю убрать слово "ото"

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0046_loc_spelL_spell_blasting.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
