### ISSUE TITLE
T1 приста (of Prophecy)

### ISSUE THREAD

**Issue by Artur91425** [WoWruRU/classicdb_ruRU#193]
"Увеличения на $s1% шанса на критический эффект заклинания "Молитва исцеления"."

"-$/1000;S1 сек. ко времени произнесения заклинания "Быстрое исцеление"."

Что за бред, надо переписать в нормальную форму.

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0047_loc_spell_priest_T1_bonus.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
