### ISSUE TITLE
T2 мага (Netherwind)

### ISSUE THREAD

**Issue by Artur91425** [WoWruRU/classicdb_ruRU#194]
"$s1%-я вероятность того, что после наложения вами заклинаний "Чародейские стрелы", "Огненный шар" или "Ледяная стрела", следующее заклинание, время наложения которого менее 10, будет наложено моментально."

10 чего? Арбузов?

**Comment by M2us** [comment]
Да ты проницателен.

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0048_loc_spell_mage_T2_bonus.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
