### ISSUE TITLE
Ошибка в тексте задания

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#2]
Шентулому? Он же Шентул.
![wow 2017-07-06 17-06-34-504](https://user-images.githubusercontent.com/29949340/27912332-871280d2-626d-11e7-87b0-7e20e8a53a30.jpg)

**Comment by Furnicarium** [comment]
мммм, действительно ли стоит оформлять любую опечатку в виде отдельной проблемы на гитхабе? Я могу таких 50 штук предоставить, собирал, пока качался. особенно радуют ошибки половые, когда мужик говорит от женского имени и наоборот.

**Comment by M2us** [comment]
Стоит.
Если бы больше людей сообщало, было бы меньше ошибок. А так увидят в игре опечатку или еще что, посмеются сами себе, и дальше пойдут. Нет бы сообщить. Важна даже мелкая ошибка в виде лишнего пробела или пропущенной запятой.

**Comment by Furnicarium** [comment]
Ну хорошо, наконец-то я понял, где можно поговорить об этом и радует то, что проект не заброшен. Разумного человека опечатки не оттолкнут, спасибо хотя бы на том, что достойный русификатор существует, ещё и бесплатный. Очень много где ругают русификаторы, призывая играть в английскую версию, но это несправедливо, Качающемуся человеку некогда сидеть и переводить текст задания - могут убить в это время или просто запустить ивент и ничего не поймёшь. Разумный человек знает, что "я сделал" и  "я сделала" переводятся одинаково "I did", поэтому смеяться и ругать не станет.
По поводу 50 я погорячился, могу предоставить 23 записанных ошибки, остальное в скринах, пока несколько

1. A troubling breeze - (обрела - обрёл, повидай (редкое, но интересное слово)!)
2. Zenn bidding не переведён
3. the road to darnassus $c вместо имени персонажа или что там должно быть, мб ошибка серва
4. the crown of the earth не переведены некоторые сдачи
5. teldrassil не переведён
6. flight to auberdine вторая часть не переведена
7. да прИбудет с тобой элуна, на полётке в аубердине (правильно писать прЕбудет)
8. easy strider living - будеМ, надо будеТ, ещё зверями-зверьми
9. tools of the highborne артИфактами, правильно артЕфактами
10. letter to delgren вторая страница не переведена

**Comment by Furnicarium** [comment]
11. favor of elune - не переведён
12. a troubling breeze 4-я часть цепочки не переведена
13. the enchanted glade 3-я часть цепочки не переведена, где посылают к Ону
14. Bashal aran - не переведна 2-я половина в тексте
15. Bashal aran - 3-я часть цепочки перепутан пол, мужик говорит "стану ли я свободной"
16. …as water cascades не переведён
17. …the fragment within (не помню точно, просто стоит пометка Ы)
18. ..thundris windweaver - ошибка $c в тексте
19. gaffer jacks - не переведён
20. Washed Ashore 2-я часть (в твоиххххх)
21. the fall of ameth alan (это былИ место)
22. Onu is meditating - не переведён
23. the absent minded prospector - не переведён

**Comment by M2us** [comment]
сделал/сделала... 
Здесь два варианта: если это обращение к игроку, тогда это ошибка локализации, не добавлена проверка на пол, и я это смогу справить. Второй же, когда сам НПС женского пола говорит о себе от лица мужского(или на оборот). Вот тогда здесь подводный камень. Решение должно быть таким: в таблице npc_text (англ), текст должен быть не только в столбце text0_0, но и еще в text0_1. И для английского варианта этот текст будет идентичен, после чего, верно привязан тем нпс, которые могут его произносить: Дусе Пироговой текст с 0_1, Грише Йоршику 0_0, Лидка Рыбак 0_1. Сейчас текст только в столбец 0_0 и он привязан ко всем перечисленным. Иными словами, здесь уже не проблема перевода, и о таком необходимо сообщать разработчиками сервера, но если говорить за русификацию, тогда разработчиками мангоса, ведь именно под него и создается локаль.

Список этот я просмотрю, но, у нас для мангоса все переведено и то, что вы встретили в игре английский текст, говорит о том, что администрация вашего сервера неверно накатила нашу базу перевода. Да и зачастую просто id отличаются. У нашего текста id 46258, а у них этот же текст под id 5, и нет 46258. Соот. данный перевод попросту будет проигнорирован. Для этого необходимо писать скрипт для сравнения текста и если он совпадает, добавлять локализацию. В любом случае, это говорить о ленивости вашей администрации. Но, повторюсь, список я, конечно же, весь осмотрю. Но лучше, если найдете ошибку именно в переведенном тексте, создайте иссуй под каждую ошибку, так проще видеть что просмотрел и исправил, а что нет. Пускай это даже будет пропущенная запятая. В идеале, это бы тоже (хотя бы) в 1 отдельный иссуй, а то уже есть кой какая работа по русификации, пока ее сделаю, могу забыть что что-то есть в комментах.
