### ISSUE TITLE
Личность лича, текст задания

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#20]
Действия персонажей обычно выделяются чем-то.
![wow 2017-07-09 03-37-29-017](https://user-images.githubusercontent.com/29949340/27990109-22f20e32-645d-11e7-961b-da913d7ab5b0.jpg)

**Comment by M2us** [comment]
[Исправлено](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0008_update_8.sql#L397)
