### ISSUE TITLE
Усадьба Балнира, текст задания

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#21]
Ну, квартал не обязательно магический. Правильно будет в "квартал магов", Во всех заданиях упоминается именно "квартал магов", здесь допущена вольность.
![wow 2017-07-09 03-39-15-028](https://user-images.githubusercontent.com/29949340/27990120-844f8952-645d-11e7-85db-1ee7ca399a5b.jpg)

**Comment by FTNonsense** [comment]
Добавляю, что трава, которая растет там там - неправильно переведена как "Львиный зев Бальнира" (исправить название предметы и сам контейнер, в котором он лежит, оба неверно переведены)

**Comment by FTNonsense** [comment]
Добавляю скрин ошибки перевода травы + баг в тексте задания по завершению. не забудьте про объект травы с таким же названием
![wow 2017-07-09 14-28-10-879](https://user-images.githubusercontent.com/29949340/27993060-f1895f3e-64b2-11e7-9319-4dcc8bc9dcb2.jpg)

**Comment by M2us** [comment]
[Исправлено.](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0026_balnir_quest_and_item.sql)
Забыл закрыть коммитом =((((
