### ISSUE TITLE
Энчант

### ISSUE THREAD

**Issue by Artur91425** [WoWruRU/classicdb_ruRU#210]
2616 locales_spellitemenchantment
"+20 к урону от заклинаний огня"

Надо переименовать в "+20 к урону от заклинаний магии огня"

25073 locales_spell
"Чары для перчаток - сила Тьмы"
Надо переименовать в "Чары для перчаток - сила тьмы" так как другие подобные чары имеют название с нижним регистром.

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0018_loc_spell_and_spellitemenchantment.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
