### ISSUE TITLE
Накинуться

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#212]
ну.. короч, в оригинале там у дебаффа написано "stunned" - то есть "оглушен", а не "stun" - т.е. "оглушение". Это важно, надо фикс. xD
![wow 2017-07-27 19-06-40-070](https://user-images.githubusercontent.com/29949340/28714905-995a72d2-73a6-11e7-8043-b2528e1f6c07.jpg)

**Comment by M2us** [comment]
Нет, не нужно. Если в случае всяких сил и т.п. мы пишем это как, какой эффект получил персонаж. То есть, сила увеличена на... то в данном случае данный вариант не подходит. Потому что персонаж может быть не только мужского пола, но и женского. Поэтому, более правильно будет сказать, что персонаж получил эффект "Оглушение.". Это в англ. все равно, stunned как женский персонаж, так и мужской.
