### ISSUE TITLE
Мучение

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#215]
одно из самых дебильных описаний способности, что я видел.
так-с, что тут у нас? мучение, ага.. что делает? "поддразнивает"? АХАХАХАХ

**_"Taunts the creature, increasing the chance that it will attack the Voidwalker."_**
переведите нормально, что-то типо "провоцирует"
![wow 2017-07-27 21-01-27-928](https://user-images.githubusercontent.com/29949340/28715853-2a614c16-73ab-11e7-965a-ea6d6d7bfb9d.jpg)

**Comment by Artur91425** [comment]
Вот тут есть варианты перевода: http://cata.wowroad.info/?spell=3716
Там справа сверху можно версии клиента переключать, посмотри что в катаклизме и в БК было)

**Comment by M2us** [comment]
Варианты БК - каты не подходят, потому что там уже изменили описание способности. 

[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0020_loc_spell_torment.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
