### ISSUE TITLE
Новобранец Элрет, последнее желание Марлы

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#216]
выдает неверный текст. забыл русский вариант заскринить, ну короч на англ. текст правильный
а на русском мне выдает "они просто идиоты.. копающие себе могилы" что-то такое, поменяйте.
![28670623-97331caa-72ea-11e7-94e6-62a86711a791](https://user-images.githubusercontent.com/29949340/28736334-6d988478-73fa-11e7-81e1-574c53880485.jpg)

**Comment by Artur91425** [comment]
Это нужно самим переводить, во всем интернете нет другого перевода. Или проверить на офе, если задание не удалили еще.
