### ISSUE TITLE
Талант, интеллект скверны

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#219]
какое еще "или"? там "и"! У всех повышает.
![default](https://user-images.githubusercontent.com/29949340/28744158-1546e43c-746c-11e7-82bd-5dbdbd5ac5b5.png)
![wow 2017-07-28 21-50-11-673](https://user-images.githubusercontent.com/29949340/28744164-1f7296ea-746c-11e7-83e4-56a37066e58e.jpg)

**Comment by Artur91425** [comment]
Да норм все. Ты одновременно можешь призвать только одного демона. В данном случае неважно "и" или "или". Мне кажется, что "или" будет правильнее.

**Comment by M2us** [comment]
По большому счету, особой разницы нет. Но я тоже считаю что с ИЛИ будет более правильно (будь там И, я бы тоже не стал заменять, потому что, как я уже сказал, большой разницы нет). 
Мы повышаем данный параметр только своему прислужнику, коих одновременно может быть только в виде 1 штуки.
