### ISSUE TITLE
Книга заклинаний лича, название предмета

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#22]
Скриншот сделать забыл, но название предмета переведено с английского неправильно. В оригинале она называется "Gunther's Spellbook" и ее как раз нужно принести Гюнтеру

**Comment by FTNonsense** [comment]
Ой, это вроде два разных предмета и я невнимательный, но все равно проверьте вторую книгу, которую выдают по заданию, ибо она должна называться " Книга заклинаний Гюнтера"

**Comment by M2us** [comment]
@FTNonsense 
id - 2833 - The Lich's Spellbook - Книга заклинаний лича.
id - 3016 - Gunther's Spellbook - Книга заклинаний Гюнтера.

Не совсем понял, что нужно?)))
