### ISSUE TITLE
Верховный палач Хадрик, Мертвое поле - "Мертвые поля"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#225]
Во-первых, устроили базу не на "Заброшенном поле", а на "заброшенной ферме" к северу.
"Our initial scouting reports of Silverpine show the rot hides have a base at an old farm to the north"
и как раз ферма находится не в "мертвом поле", а в "Мертвых полях"
"hides have a base at an old farm to the north, **_the Dead Fields._**"
**_поэтому здесь надо фиксануть название локации еще и в игровом интерфейсе, на карте._**
и да, везде, где упоминается "Мертвое поле" в единственном числе - ошибка, это "Мертвые поля", ну я подчеркнул на скрине.
"Go to the Dead Fields and assault the rot hides. "
![wow 2017-07-28 22-32-36-739](https://user-images.githubusercontent.com/29949340/28744482-dce3c96e-7472-11e7-9082-353e6981287c.jpg)

**Comment by FTNonsense** [comment]
Там еще в целях задания исправить, где убивать гноллов на "Мертвом поле", хотя должно быть на "Мертвых полях"

**Comment by FTNonsense** [comment]
![wow 2017-07-28 22-46-56-828](https://user-images.githubusercontent.com/29949340/28744491-1cf18e1a-7473-11e7-8128-07c18460d742.jpg)

**Comment by Artur91425** [comment]
хм... но ведь там в игре всего одно поле с теми гноллами.
