### ISSUE TITLE
Наложение чар

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#226]
Короче, даже не спрашивайте, как я до такого додумался. Но пытался зачарить штаны, когда в рецептах были только чары на наручи. Не суть, при попытке мне выдавало такой текст, который 100% переведен промтом и неправильный.
Английского я не видел, но догадываюсь, что там должно быть написано что-то типо, что накладывать чары надо на другой предмет.
![wow 2017-07-28 23-00-53-817](https://user-images.githubusercontent.com/29949340/28744530-1ed16448-7474-11e7-9dc0-403f38172bc0.jpg)

**Comment by Artur91425** [comment]
Что-то я не могу воспроизвести это сообщение. Мне пишет "Этот предмет не годится в качестве цели."
