### ISSUE TITLE
Канал здоровья

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#233]
Питомцу? Но у чернокнижников не может быть питомцев, только демоны
![wow 2017-07-29 18-07-53-250](https://user-images.githubusercontent.com/29949340/28753045-4f58834c-753e-11e7-9d0a-319ad324f910.jpg)

**Comment by FTNonsense** [comment]
еще не заметил. что это еще за "плюс 5 сек"? Не видел в оригинале, но подозреваю, что это не нормально.
![wow 2017-08-01 02-01-39-722](https://user-images.githubusercontent.com/29949340/28823136-2e0c4d00-76cd-11e7-83c5-6b840388fa9e.jpg)

**Comment by FTNonsense** [comment]
**_и тут еще надо бы не "если заклинатель поддерживает заклинание", а "пока заклинатель..."_**

и много слов "Заклинание" и "заклинатель" ваще.
![wow 2017-08-15 01-00-16-624](https://user-images.githubusercontent.com/29949340/29316090-95f24c0c-81d7-11e7-97b2-e5e8662fd356.jpg)

**Comment by M2us** [comment]
Ага, именно питомцу. Не знаю, почему принято называть их петами.
>pet every second

Плюс? Нормально, на англ там 11 Health, plus 5 per sec

[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0021_loc_spell_health_funnel.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
