### ISSUE TITLE
Проклятие безрассудствва

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#240]
Прямо в магазе у учителя, опечатка.
должно быть "атаки"
![wow 2017-07-29 20-30-44-227](https://user-images.githubusercontent.com/29949340/28754222-57d828a6-7552-11e7-9cdf-7dc1156b0c0b.jpg)

**Comment by FTNonsense** [comment]
![wow 2017-08-15 01-00-52-656](https://user-images.githubusercontent.com/29949340/29316165-e1f6ed2e-81d7-11e7-9417-71db83780ea3.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0022_loc_spell_curse_of_recklessness.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
