### ISSUE TITLE
Аптекарь Юхан, новая чума

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#25]
Обычно аптекарь Юхан всегда вежливо обращался к игроку на "вы", но в последнем задании переменил свое отношение. 
![wow 2017-07-09 14-48-23-650](https://user-images.githubusercontent.com/29949340/27993265-cac2a108-64b7-11e7-8bfa-2b7484f75e27.jpg)
Вообще лучше проверить все его задания на наличие такой путаницы

**Comment by M2us** [comment]
[Исправлено.](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0022_apothecary_johaan_quests.sql)
