### ISSUE TITLE
Замшелые руки

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#255]
метелица на офе поправила как описание способности, так и описание дебаффа на цели, так что и вам лучше заменить.

"Makes an enemy likely to drop its weapon. Lasts 15 sec." - "Высокая вероятность уронить оружие. Время действия – 15 сек."
"Chance to drop melee weapon when attacking." - "Вы можете выронить оружие ближнего боя при атаке."
![wow 2017-08-01 00-31-36-930](https://user-images.githubusercontent.com/29949340/28822270-af3a7acc-76c9-11e7-9d26-ecf79076245f.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0023_loc_spell_moss_covered_hands.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
