### ISSUE TITLE
Скользкий мох" - "Замшелые ноги" или типо того

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#256]
Ну, тут неправильно переведено название способности, которая в оригинале тупо аналогична прошлому моему репорту, только касается ног.
"Moss Covered Feet" - "Замшелые ноги"
"Makes an enemy likely to fall down when hit. Lasts 3 min." - "Вероятность упасть при нанесении удара. Время действия – 15 sec."
дебафф:
"Chance to fall down when hit." - "Вы можете упасть при получении удара."
![wow 2017-08-01 00-58-29-242](https://user-images.githubusercontent.com/29949340/28822518-99f74a04-76ca-11e7-8233-40aebb8d2b4c.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0024_loc_spell_moss_covered_feet.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
