### ISSUE TITLE
Жгучая боль, уровень 1

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#258]
На первом уровне урон вроде бы 34-43, так что в локализации ошибка, проверьте на всякий случай.
затем тут перевод некорректный. что значит "представляет высокий уровень угрозы?" Я знаю, как действует аггро и что это.
правильно будет **_"Создает высокий уровень угрозы"_** - так переведено у всех нормальных способностей, того же жреца к примеру.
![wow 2017-08-01 01-43-44-998](https://user-images.githubusercontent.com/29949340/28822884-1ae510d2-76cc-11e7-9649-f294be0962ba.jpg)

**Comment by Artur91425** [comment]
На числа не смотри. Они к локали не относятся. Они там записаны все в виде переменных $s1 и данные поступают с сервера.

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0025_loc_spell_searing_pain.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
