### ISSUE TITLE
Погибельник, текст задания

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#26]
Действия персонажей обозначаются звездочками или скобками.
![w0sjlbjzk6o](https://user-images.githubusercontent.com/29949340/27993651-fbb663b0-64be-11e7-805f-a651c48cc738.jpg)

**Comment by M2us** [comment]
[Исправлено.](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0008_update_8.sql#L363)
