### ISSUE TITLE
Обезображенный труп

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#267]
Не согласен, что "beaten" - переводится как "обезображенный", в конце концов труп не выглядит ужасным, да и по истории этот орк отбивался от полчищ иглошкуров, а не какой-нибудь армии Плети.
тот же труп Маура зловещего тотема из Огненной пропасти, который тоже был "beaten" в тексте задания - перевели как "побитый" ли что-то в этом роде, подумайте.
![wow 2017-08-02 10-47-00-567](https://user-images.githubusercontent.com/29949340/28900381-c982c356-7801-11e7-97db-8761cee50ae8.jpg)

**Comment by FTNonsense** [comment]
а, еще у нее текст не совсем правильно переведен.
"The body is that of a female orc warrior.$B$BIt is clear that she died in battle, probably against the quilboar in the area."
в первой страке указывается, что это "**_женщина-орк_**", подчеркиваю.
затем, тут во вторм предложении правильно будет не "Несомненно", а "**_очевидно_**" - игрок делает как бы вывод для себя.
![wow 2017-08-02 10-47-03-417](https://user-images.githubusercontent.com/29949340/28900437-3d02466c-7802-11e7-994d-944645fc965d.jpg)

**Comment by Artur91425** [comment]
И тут тоже все верно. Слова "Орк и Воин" не имеют женского рода. "Несомненно" тоже подходит как вывод для себя. Имеется ввиду, что эта мысль не поддается сомнениям. В данном случае слова "Несомненно" и "Очевидно" являются синонимами.
