### ISSUE TITLE
Иветта Фартинг, недоставленное письмо, текст задания

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#27]
Действия персонажей... ну понятно, а еще там с Тарменом и его именем проблема, но вроде уже фиксили.
![o-mn0lwyx3k](https://user-images.githubusercontent.com/29949340/27993671-6437c3f2-64bf-11e7-919c-2f6cf0b40f14.jpg)

**Comment by M2us** [comment]
[Исправлено.](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0008_update_8.sql#L380)
