### ISSUE TITLE
Пора веселиться - "Повеселимся"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#272]
это магия и ее баф уже перевела метелица более правильно. Я думал-думал, как исправить, а потом сошелся сам с собой во мнении, что и у метелицы нормальный перевод.
вот, сравните оригинал и смотрите, что я предлагаю:
бафф:
Повеселимся! Магия 
В воздухе разлита радость.
Осталось: 2 мин

заклинание:
Повеселимся!
Радиус действия: 30 м
Мгновенное действие
Требует уровень: 1

это намного корректнее, да вы и сами мне писали, что лучше ставить фиксы метелицы.
![wow 2017-08-02 11-50-05-447](https://user-images.githubusercontent.com/29949340/28927404-7d9bcd1e-787b-11e7-978d-30687c47863a.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0026_loc_spell_party_time.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
