### ISSUE TITLE
Руины Лордаэрона - "Руины Лордерона"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#274]
тут, я думаю, очевидна ошибка.
![wow 2017-08-02 14-44-04-285](https://user-images.githubusercontent.com/29949340/28928627-bdaf06ac-787e-11e7-89fc-39173aed7e6b.jpg)

**Comment by Artur91425** [comment]
лол, ты предлагаешь карту в паинте править? xD

**Comment by M2us** [comment]
- Изменено название Ruins of Lordaeron что в Подгороде с
"Руины Лордаэрона" на
"Руины Лордерона".
Изменения будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016

P.S.: просто взято с ЛК. И не пришлось ничего перерисовывать. 

![5v92ysix-ai](https://user-images.githubusercontent.com/17622429/29040433-aa0dc106-7bb7-11e7-81d7-57520cfb2d5e.jpg)
