### ISSUE TITLE
Захария Пост

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#28]
Говорит о себе в женском лице.
![dhsw-v1jeoy](https://user-images.githubusercontent.com/29949340/27993676-841753a4-64bf-11e7-9a21-33c31d0b409e.jpg)

**Comment by M2us** [comment]
[Исправлено.](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0008_update_8.sql#L385)
