### ISSUE TITLE
Оглушения на примере "Дымовой шашки"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#281]
есть много способностей, при которых игроки получают дебафф, где в оригинале стоит метка "stunned".
в нашей же локали половина скилов переведена как "оглушение", а другая половина как "оглушен" - второй вариант будет, конечно, более правильным. смотрите у метелицы да и опять же, собственно, оригинал. "stunned", не "stun" - оглушен. Это огромная и тяжелая работа, но проверьте все дебаффы с текстом "stunned" и исправьте, если можно.
![wow 2017-08-02 12-47-18-948](https://user-images.githubusercontent.com/29949340/28946697-f82abe50-78bc-11e7-8b0b-dc1af6321d37.jpg)

**Comment by FTNonsense** [comment]
аналогично со споосбностями на "обездвижевание" на прмиере "Общих уз".
так "immobilized", а не "immobilize' - то есть "Обездвижен", а не "обездвижевание".
![wow 2017-08-04 23-51-19-364](https://user-images.githubusercontent.com/29949340/28995067-9f6f7f74-79ef-11e7-8fda-0e6d34a63b49.jpg)
хотя не знаю, вам решать

**Comment by FTNonsense** [comment]
и еще здесь
![wow 2017-08-07 18-18-22-291](https://user-images.githubusercontent.com/29949340/29085480-7e3fb59c-7c80-11e7-9121-72c121579366.jpg)
"thundershock" Аругала, если что

**Comment by FTNonsense** [comment]
**_и кстати, тут должна быть не "сеть", а "паутина". Просто к слову, что у бандитов Синдиката в Хилсбраде, я уже репортил, сеть как раз "паутиной" зовется..._**
"web" всхе лоу лвл пауков на примере "Deepmoss Webspinner"
![wow 2017-08-07 19-07-09-182](https://user-images.githubusercontent.com/29949340/29085919-da412e6a-7c81-11e7-90cc-7fedad8fcdb1.jpg)

**Comment by FTNonsense** [comment]
вот еще один пример.
в оригинале там "stunned" - т.е. "Оглушен".
![wow 2017-08-13 18-57-49-174](https://user-images.githubusercontent.com/29949340/29275161-457591ba-811b-11e7-8887-d9eee8faed85.jpg)
абилка наг "daggerspine"

**Comment by M2us** [comment]
Как уже писалось, нельзя к девушке применить слово: "Оглушен", должно быть - "Оглушена". Соот., нужно выбрать что-то нейтральное, такое, чтобы подходило как к мужскому полу, так и женскому. Оглушение в данном случае - лучший вариант.

В англ. там все равно, stunned и stun может быть как девушка, так и парень.
