### ISSUE TITLE
Запугивание

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#283]
не совсем верное описание дебаффа, метелька уже все пофиксила у себя, давайте и вы.
вот как должно быть:

Запугивание Магия
Бегство в страхе.
Осталось: 3 секунды

![wow 2017-08-02 14-07-47-030](https://user-images.githubusercontent.com/29949340/28947140-54142542-78bf-11e7-85d5-ebe548cdec11.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0027_loc_spell_terrify.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
