### ISSUE TITLE
Талант, нечестивая сила

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#287]
Подобное уже встречалось ранее в https://github.com/WoWruRU/classicdb_ruRU/issues/219
здесь все аналогично - не "или", а "и".
![wow 2017-08-02 15-23-00-844](https://user-images.githubusercontent.com/29949340/28967822-0b90a650-792e-11e7-8108-7d70d38e73b0.jpg)

**Comment by Artur91425** [comment]
Тоже самое, что и в https://github.com/WoWruRU/classicdb_ruRU/issues/289

**Comment by M2us** [comment]
Ответ в #219
