### ISSUE TITLE
Талант, выносливость скверны

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#289]
снова не "или, а "и".
https://github.com/WoWruRU/classicdb_ruRU/issues/287
https://github.com/WoWruRU/classicdb_ruRU/issues/219
![wow 2017-08-02 15-27-59-128](https://user-images.githubusercontent.com/29949340/28968029-17675b6c-792f-11e7-9442-99ca446b72f0.jpg)

**Comment by Artur91425** [comment]
все правильно, там идет перечисление и у тебя этот талант единовременно повышает у одного демона. Поэтому там должно быть "или". Если бы он повышал у всех сразу(что невозможно), тогда бы стояло "и".

**Comment by M2us** [comment]
Ответ в #219
