### ISSUE TITLE
Марион Зов, Меннит Каркад, текст задания

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#29]
Говорит о себе в мужском лице.
![67rry-9qdz4](https://user-images.githubusercontent.com/29949340/27993696-b40f59c6-64bf-11e7-9527-41188a548a8b.jpg)

**Comment by M2us** [comment]
[Исправлено.](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0008_update_8.sql#L389)
