### ISSUE TITLE
Повреждение сухожилий

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#291]
там вроде как скорость снижается на 25%, проврьте по базе, мб ошибка.

![wow 2017-08-02 19-53-06-972](https://user-images.githubusercontent.com/29949340/28968663-3a5f1170-7932-11e7-9ecb-8cd0dd8b8794.jpg)

**Comment by Artur91425** [comment]
по базе стоит $s1%, то есть число это берется с сервера, причем для каждого моба свое. Я вот потестил ща этот спелл и у меня были варианты 80, 79, 74 %

**Comment by M2us** [comment]
Немного изменил описание способности.

[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0028_loc_spell_tendon_rip.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
