### ISSUE TITLE
Ритуал призыва

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#292]
тут странное предложение, которого нет в оригинале и которое путает нахрен все.
вот оригинал:

"Begins a ritual that summons the targeted group member. Requires the caster and 2 additional party members to complete the ritual. In order to participate, all players must be out of combat and right-click the portal and not move until the ritual is complete."

а теперь смотрите на подчеркнутое предложение. его не должно быть, к тому же в нем грубая ошибка: требуется не 2 участника группы, а 3. Это предложение стоит убрать из описания вообще, а первое дополнить как в оригинале, чтобы получилось: **_"Ритуал создания портала призыва, с помощью которого можно призвать выбранного участника группы."_**

да, подчеркнутое предложение надо к черту убрать, оно глупое и его не должно быть.
![wow 2017-08-02 20-47-53-243](https://user-images.githubusercontent.com/29949340/28968810-db306b8a-7932-11e7-9495-82b2803d05f9.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0029_loc_spell_ritual_of_summoning.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
