### ISSUE TITLE
Жидкая руда

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#296]
описания дебаффа слега неверное, метелица у себя уже поправила, пора и вам.
вот как у них и как надо:
Жидкая руда
В течение 20 сек. наносится 140 ед. урона от огня.
Скорость передвижения снижена на 40%.
![wow 2017-08-02 21-33-38-748](https://user-images.githubusercontent.com/29949340/28969432-a43e4748-7935-11e7-9d50-8adcc12babbd.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0030_loc_spell_melt_ore.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
