### ISSUE TITLE
Пронзенная броня - "Проколотая броня"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#297]
во-первых, судя по англу "pierce armor" - ее имена прокалывают, да и как, к прмиеру, шахтеры, фактически безоружные, у которых есть эта способность, могут аж "пронзить" броню? не, они ее киркой максимум проколят, да оно и логично, прокол - ослабил на немного, а пронзил - так ваще уничтожил, там на все 100% понижать надо.

далее, метелицы пофиксила описание дебаффа, так что и  вы фиксуйте.
вот как должно быть:

"Проколотая броня"
Показатель брони снижен на 50%.
![wow 2017-08-02 21-39-14-980](https://user-images.githubusercontent.com/29949340/28969604-45531e10-7936-11e7-810b-7a7dc02cebfc.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0031_loc_spell_pierce_armor.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
