### ISSUE TITLE
Каннибализм

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#298]
опечатка, должно быть "находящиеся".
а вообще, переделайте весь перевод способности, как на офе. сами же говорили, что правки метелицы будете ставить, если такое есть, вот как там:
"При активации восстанавливается 7% от максимального запаса здоровья в 2 сек. в течение 10 сек. Действует только на трупы гуманоидов или нежити в пределах 5 м. Любое передвижение, действие или получение урона во время каннибализма прерывает этот процесс."
![wow 2017-08-04 23-29-12-252](https://user-images.githubusercontent.com/29949340/28995045-317acc44-79ef-11e7-8893-6f81643068b1.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0032_loc_spell_cannibalize.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
