### ISSUE TITLE
Кузнечное дело

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#299]
опечатка. должно быть **_"отличное оружие и броню"._**
![wow 2017-08-05 00-18-33-584](https://user-images.githubusercontent.com/29949340/28995072-c8170898-79ef-11e7-8d96-b3ca146e891e.jpg)

**Comment by M2us** [comment]
[Изменения ](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0060_loc_spell_blacksmithing.sql)будут приняты в следующем обновлении после 28.09.2017.
