### ISSUE TITLE
Ошибка в переводе способности НИПа

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#3]
Прикосновение Когтеврана? Хотя этот клан плети, вроде как, везде упоминается как Коготь Ворона (в заданиях, именах НИПов), значит и это должно быть. 
![wow 2017-07-06 23-02-58-217](https://user-images.githubusercontent.com/29949340/27936111-434c7922-62c0-11e7-934d-52430b39e748.jpg)
![wow 2017-07-06 23-03-02-149](https://user-images.githubusercontent.com/29949340/27936110-43472cd8-62c0-11e7-900f-e64cd6941931.jpg)

**Comment by M2us** [comment]
- Изменено название способности "Touch of Ravenclaw" с
"Прикосновение Когтеврана" на
"Прикосновение Когтя Ворона".


Изменения будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
