### ISSUE TITLE
Бетор Ледострел, личность лича, текст задания

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#30]
Действия персонажей выделяются чем-то, см. оригинал.
![zcqbmiq0xxy](https://user-images.githubusercontent.com/29949340/27993705-ede05eca-64bf-11e7-9fe5-7a7c343ae321.jpg)

**Comment by M2us** [comment]
[Исправлено.](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0008_update_8.sql#L397)
