### ISSUE TITLE
Разъедающий яд - "Едкий яд"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#302]
думаю, что "corrosive" стоит перевести как "едкий", потому что "разъедающий" - как-то.. 
еще в варкрафте 3 у ночных эльфов, химер, была абилка "corrosive breath" которую надо было исследовать, а наши локализаторы (локаль вк3 была одна из лучших) перевели это как "едкое дыхание".
![wow 2017-08-05 15-48-30-101](https://user-images.githubusercontent.com/29949340/29002942-9bc1e360-7abe-11e7-9243-d2887f774366.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0033_loc_spell_corrosive_poison.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
