### ISSUE TITLE
Карендин Халгар, чистые сердца

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#303]
во-первых, название задания "hearts of the pure" следует перевести как "Сердца невинных" или, ну, в крайнем случае "сердца чистых людей" - там в английском упор не на чистоту сердец, а на личностей, в чьих грудях эти сердца бьются.

далее перевод дивления "скорости работы" в рамках локализации неверно, это дословный перевод. там имеется ввиду "**_скорости твоего обучения_**" - типо чернокнижник быстро учится, что впечатлило Карендина,
![wow 2017-08-05 16-30-21-900](https://user-images.githubusercontent.com/29949340/29003392-49c5fed0-7ac7-11e7-85d9-d7a0888a1ae6.jpg)

**Comment by FTNonsense** [comment]
вкладка "завершени".
тут вообще весь перевод неверный, даже подчеркивать не буду.
там в оригинале:
"The heart of a goodly man seems much the same as any, when you see it like this, don't you think?

Perhaps we possess something of a... different... view on the subject. These will do, though. I have no doubt that a succubus would be attracted by their purity."
вот набрасываю нормальный перевод:
**_"Сердца добрых людей кажутся такими же, как и сердца остальных, если смотреть на них отсюда_** (типо вырванных из тел), **_ты так не думаешь?_**

**_Может быть у что-то вроде... разных взглядов на это. Так или иначе, эти подойдут. Я не сомневаюсь, что суккуба привлечет их чистота."_**
![wow 2017-08-05 16-30-32-100](https://user-images.githubusercontent.com/29949340/29003467-34e75274-7ac8-11e7-9cb6-2e345f513d32.jpg)

**Comment by Artur91425** [comment]
> далее перевод дивления "скорости работы" в рамках локализации неверно, это дословный перевод. там имеется ввиду "скорости твоего обучения" - типо чернокнижник быстро учится, что впечатлило Карендина,

Ты уверен, может там он удивляется как быстро добыл сердца?
