### ISSUE TITLE
Пища для ума

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#309]
посмотрите значение на англ. ты же вроде "**_33 ед. маны"._**
плюс, уберите "сек", переименуйте в **_"секунду"_**
![wow 2017-08-05 19-35-52-417](https://user-images.githubusercontent.com/29949340/29007720-82c79dd0-7b1a-11e7-80f8-2b382ab976c2.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0034_loc_spell_brain_food.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
