### ISSUE TITLE
Утраченный навык: Тень - "утраченный навык: тьма"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#318]
переименовать заклинание в **_"утраченный навык: тьма"_**
плюс исправить описание на:
**_"Умение творить заклинания темной магии снижено на 100."_**
чекайте фиксы метелицы.
![wow 2017-08-05 23-30-36-780](https://user-images.githubusercontent.com/29949340/29014179-c6c664d8-7b58-11e7-8349-c4c583b7a518.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0036_loc_spell_forsaken_skill_shadow.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
