### ISSUE TITLE
Утраченные навыки - "утраченный навык"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#319]
дебафф называется "forsaken ability" - в единственном числе, так что переименуйте **_это в "утраченный навык"_**
![wow 2017-08-05 23-30-40-180](https://user-images.githubusercontent.com/29949340/29014240-1f433e4c-7b59-11e7-8e5f-2b70d9944338.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0036_loc_spell_forsaken_skill_shadow.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
