### ISSUE TITLE
Страж смерти Буржес, доказательство верности, текст задания

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#32]
10 перстней алого ордена, а не алых перс
![0rohuhwgdeg](https://user-images.githubusercontent.com/29949340/27993729-3d7cc34c-64c0-11e7-8078-50a8d976182b.jpg)
тней - разница большая

**Comment by M2us** [comment]
[Исправлено.](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0008_update_8.sql#L407)
