### ISSUE TITLE
Утраченный навык: лук - "утраченный навык: луки"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#320]
**_переименовать в "утраченный навык: луки"_** - чекайте метелицу.
**_поменять описание на "Навык владения луком снижен на 100."_** - тоже чекайте ее же.
![wow 2017-08-05 23-31-13-227](https://user-images.githubusercontent.com/29949340/29014309-6dccab52-7b59-11e7-880a-80cf7692fda9.jpg)
там этих скилов полно, прочекайте все,  у большей части неправильные описания и названия, чекайте метелицу и тупо исправьте.
просто в базе вбейте "утраченный навык"

**Comment by FTNonsense** [comment]
здесь тоже на:
**_"Навык владения палицей снижен на 100."_**
![wow 2017-08-07 17-51-05-375](https://user-images.githubusercontent.com/29949340/29078946-dff42930-7c6c-11e7-9e60-35e5815d97e9.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0036_loc_spell_forsaken_skill_shadow.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
