### ISSUE TITLE
Схема: динамит "pro-1oo-брос" - "Схема: динамит "про-100-брос"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#321]
не понятно, зачем оставили на англ, в русском эта игра слов так же работает.
переименуйте все предметы и описания с упоминанием этого "pro-100" на "про-100"
вот приблизительный список:
item=6716
item=18588
item=6714
item=18650

spell=8332
spell=23069
spell=8331
spell=8339
spell=23000
spell=23001
![wow 2017-08-05 23-35-02-749](https://user-images.githubusercontent.com/29949340/29014449-17d78ec8-7b5a-11e7-9197-76cc2a26c8be.jpg)

**Comment by Artur91425** [comment]
а какая игра слов с "EZ-Thro"? А то я в англ. не силен и не понимаю. :(

**Comment by M2us** [comment]
Ох уж этот любитель игры слов.
На англ. итем этот называется Ez-Thro Dynamite, а не какие-то там Pro-100....

Здесь тот же случай что и с хилтор перисс или как там ее, которую добавили в БК.
А именно, это отсылка (пасхалка) к какой-то старой буржуйской команде, связь с которой кроется в этих Ez. И также на ру. сделали отсылку к знаменитой на то время СНГ команде, некоторые из участников которой уже выступают в Нави. А известна эта тима была как Pro100.

Даже я был тогда наслышен Pro100, они тогда врывались и всем выписывали люлей. )
