### ISSUE TITLE
Бесцветный ворг - "Блеклый ворг"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#322]
ну, цвет-то у него есть - белый с помесью светло-синего,  да и "bleak worg" - **_можно отлично локализировать, в рамках контекста, как "блеклый ворг"._**, то есть он не ворг, но еще не призрак. призраки воргов там есть - "волчий ужас" - чекните этих нипов.
![wow 2017-08-05 23-46-43-647](https://user-images.githubusercontent.com/29949340/29014509-65cd9672-7b5a-11e7-8a2c-24c65f7d5d3b.jpg)

**Comment by Artur91425** [comment]
"bleak" переводится как "мрачный" и вариант "Мрачный ворг" мне кажется лучше.
