### ISSUE TITLE
Нерешительность

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#324]
пытался перевести "Wavering Will" как-то иначе, ибо "нерешительность" очень близко, но не точно, однако не смог. подумайте над этим.
так или иначе, надо описание спела переделать, вот чо у метелицы:

**_"Нерешительность  Магия_**
**_Интервал между атаками увеличен на 25%._**
**_Скорость произнесения заклинаний снижена на 20%._**
**_Скорость передвижения снижена на 20%."_**
![wow 2017-08-07 17-20-52-081](https://user-images.githubusercontent.com/29949340/29075855-c3bf224a-7c64-11e7-97e4-7eaf74f328dc.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0011_loc_spell_wavering_will.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
