### ISSUE TITLE
Воргены в Крепости Темного Клыка

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#327]
в общем, у всех воргенов в оригинале имена имеют такой тип: "Shadowfang имя НИП"
У нас же рознится на, к примеру "Ворген Темного Клыка" и "Ворген из крепости Темного Клыка"
надо поправить, и мне трудно решить, что правильнее.

к прмиеру можно взять Деревню ПОгребальных Костров, что рядом, там "Pyrewood Watcher", а у нас "Дозорный из деревни Погребальных Костров" - вроде все верно.

короче, суть репорта в том, что надо систематизировать всех НИПов в Крепости Темного Клыка, чтобы они были либо "из крепости", либо просто "Темного Клыка". решайте.

![wow 2017-08-07 17-40-21-190](https://user-images.githubusercontent.com/29949340/29078477-98128716-7c6b-11e7-9afa-a2a8f1d17b05.jpg)

![wow 2017-08-07 17-51-31-806](https://user-images.githubusercontent.com/29949340/29078697-31a0963e-7c6c-11e7-999f-b614eb3690de.jpg)

**Comment by Artur91425** [comment]
учитывая логику рассуждения с "Pyrewood Watcher", то и воргены должны быть "из крепости"

**Comment by FTNonsense** [comment]
https://github.com/WoWruRU/classicdb_ruRU/issues/373
в задании упоминаются **_"волшебники из крепости Темного Клыка"_**
наверно, ндао действительно "из крепости"
