### ISSUE TITLE
Вопли прошлого

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#328]
**_должно быть "произносить" заклинания._**
![wow 2017-08-07 17-41-57-335](https://user-images.githubusercontent.com/29949340/29078601-e3c6c186-7c6b-11e7-83a6-9846a4522b8e.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0037_loc_spell_screams_of_the_past.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
