### ISSUE TITLE
Формула: зачаровывание обуви - ловкость III ступень и серьезные изменения

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#329]
ну, слово "ступень" надо убрать, в других рецептах этого нет, да и название от этого еще длинее.

**_теперь, когда с меньшим багом покончено, нам надо обсудить очень серьзную ошибку. Дело в том, что как таковой "ловкости I" два и так далее - нет. Это как с зельями, есть "lesser" "medium" "large'.
мы с вами обсуждали уже подобное, но с зельями, и вы согласились. поэтому.. исправьте лучше, хоть названия будут короче и красивее._**

помимо названий предметов, когда чаришь, то там еще как-бы скилл с названием, его тоже исправьте.
![wow 2017-08-07 18-36-14-787](https://user-images.githubusercontent.com/29949340/29085660-fbe6dd22-7c80-11e7-9420-12dd2a94c348.jpg)

**Comment by M2us** [comment]
11168  Формула: зачаровывание щита – блок, I ступень                                           
 16214  Формула: зачаровывание браслетов – интеллект, III ступень                     
 16219  Формула: зачаровывание перчаток – ловкость, III ступень                         
 16222  Формула: зачаровывание щита – дух, V ступень                                             
 16242  Формула: зачаровывание нагрудника – мана, IV ступень                              
 16245  Формула: зачаровывание обуви – ловкость, III ступень                               
 16246  Формула: зачаровывание браслетов – сила, V ступень                                 
 16253  Формула: зачаровывание нагрудника – все характеристики, III ступень
