### ISSUE TITLE
Колман Фартинг, упоминание

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#33]
Потерял точно где, но где-то либо в этом задании, либо в другом его называют Колуман, что неверно, ибо везде он уже записан как Колман. задание семейный склеп
![uqkeo-mmv_e](https://user-images.githubusercontent.com/29949340/27993739-7966060c-64c0-11e7-8e0a-0a51b19b039d.jpg)

**Comment by M2us** [comment]
[Исправлено](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0008_update_8.sql#L411)
