### ISSUE TITLE
Муглаш, Ворша хлестунья

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#332]
первое - "She has attacked our outpost, each time unprovoked, laying waste to anything that falls in her path."
я бы дополнил перевод более корректно:
**_"Она нападает на нашу заставу, каждый раз без причины, опустошая все на своем пути."_**

и второе: "But I am ready, <name>. I have prepared to best the hydra and end these attacks on Zoram'gar."
**_тут скорее не "уничтожить", а "одолеть"_** гидру, "to best' - английский, типа. хд
![wow 2017-08-07 19-46-04-017](https://user-images.githubusercontent.com/29949340/29099498-dbbb935e-7cb6-11e7-9310-2b28dc6188d6.jpg)

**Comment by FTNonsense** [comment]
еще здесь.
первое:
" Help him by putting the brazier out, then protect him as you fight against the Naga."

лучше бы сделать что-то типо:
"Помогите ему потушить жаровню,а затем защищайте его от наг."
![wow 2017-08-07 19-46-33-199](https://user-images.githubusercontent.com/29949340/29099570-3f11c46e-7cb7-11e7-9004-7d31ffe820b9.jpg)

**Comment by FTNonsense** [comment]
и в зарешении.
у гонца Песни войны рандомно моделька мужчины или женщины генерируется.
в оригинале там все "I" да "I", а у нас из-за этого путаница полов.
переделайте, замените чтоль нейтральными фразами.
![wow 2017-08-07 19-53-08-712](https://user-images.githubusercontent.com/29949340/29123559-32dcff68-7d27-11e7-9051-6da67573fabd.jpg)

**Comment by Lichery** [comment]
Только не
"Она нападает на нашу **заставку**, каждый раз без причины, опустошая все на своем пути.", а
"Она нападает на нашу **заставу**, каждый раз без причины, опустошая все на своем пути."
