### ISSUE TITLE
Замедление

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#337]
способность Леди Саревесс. исправьте описание дебаффа, как у метелицы на:
**_"Замедление  Магия_**
**_Скорость передвижения снижена на 35%._**
**_Скорость атаки снижена на 35%."_**
![wow 2017-08-08 22-42-55-950](https://user-images.githubusercontent.com/29949340/29126143-9bc01a22-7d2e-11e7-89f2-ad7629304e08.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0038_loc_spell_slow.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
