### ISSUE TITLE
Колючий членистоног - "Колючее ракообразное"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#338]
**_в общем-то "crustacean" переводится как "ракообразное, да и все остальные крабы в Непроглядной пучине переведены именно как "ракообразное", так что исправьте._**
![wow 2017-08-08 23-16-31-897](https://user-images.githubusercontent.com/29949340/29126477-85dcc484-7d2f-11e7-88b6-2e39b597863d.jpg)

**Comment by Artur91425** [comment]
Тоже считаю, что тут не нужно исправлять. Получится же косноязычно как-то и некрасиво. "Колючее ракообразное"...
