### ISSUE TITLE
Повелитель стихий из культа сумеречного молота - "Элементалист из культа сумеречного молота"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#339]
ну, "elementalist" в переводе далеко не "повелитель стихий". да и мы перевели с английского аквамантов как аквамантов. Давайте  и элементалистов так же, тут и без этого понятно, что это заимствованное слово и что оно значит. да и в варкрафте "стихии" зовутся даже больше "элементалями", так что "элементалист" - понятнее.
![wow 2017-08-08 23-38-06-146](https://user-images.githubusercontent.com/29949340/29126568-ca9eea34-7d2f-11e7-8dfd-7a1bd6251ed7.jpg)

**Comment by Artur91425** [comment]
Да не, бред. Во что такое "элементалист"? Мне не понятно. А "Повелитель стихий" сразу понятно, кто это и что это значит.
