### ISSUE TITLE
Рецептура смерти, летящая кровь, название предмета

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#34]
Название крови паука - Летящая кровь - нечто иное, как перевод промта. Просто посмотрите англ вариант и станет понятно, что это просто дебильный перевод.
![hfxyyubz4sm](https://user-images.githubusercontent.com/29949340/27993745-cd3236e8-64c0-11e7-9bdd-3c9f3336e659.jpg)

**Comment by Lichery** [comment]
Collect 6 Grizzled Bear Hearts and 6 samples of Skittering Blood and deliver them to Master Apothecary Faranell in the Undercity.

**Comment by FTNonsense** [comment]
Нашел отгадку. Пауки обитают в локации, именуемой "Skittering Dark" - что переведено как "Струящаяся тьма" - очень успешно на мой взгляд. И теперь внимание.. кровь называется "skittering blood" - то есть переводим по аналогии и.. "Струящаяся кровь" - здесь связь между локацией, пауками и предметов. Вопрос решен.
