### ISSUE TITLE
"Термит Чумных земель" -> "Чумной термит"

### ISSUE THREAD

**Issue by Artur91425** [WoWruRU/classicdb_ruRU#341]
12120
Есть аналогичные мобы:
  'Plagued Insect',
  'Plagued Maggot',
  'Plagued Rat',
Они все переведены как "Чумные" и только термит переведен как "Термит Чумных земель"

**Comment by M2us** [comment]
Потому что они все Plagued - Чумной, а этот Plagueland - Чумных земель.
