### ISSUE TITLE
Каналы

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#343]
так ведь должно быть "на канале"
![wow 2017-08-10 19-17-15-152](https://user-images.githubusercontent.com/29949340/29178948-14093dbc-7e04-11e7-8f9f-e7883062c2a2.jpg)

**Comment by FTNonsense** [comment]
и еще вот здесь, н езнаю баг ли это, поэтому сюда напишу.
когда изучаешь "первую помощь" на умельца, то она зовется "умелец первой помощи", но заклинание изучения почему-то переводится как "Первая помощь (умелец". МОжет заменить на "Умелец первой помощи"?
![wow 2017-08-10 22-07-17-539](https://user-images.githubusercontent.com/29949340/29215487-353a27b8-7ebc-11e7-8b78-6f5d5e6aef58.jpg)

**Comment by FTNonsense** [comment]
то же и с кулинарией
![wow 2017-08-10 23-00-10-156](https://user-images.githubusercontent.com/29949340/29223386-6e764456-7ed7-11e7-8787-887633b2b866.jpg)

**Comment by Lichery** [comment]
однозначно нужно приводить все к единому виду)
