### ISSUE TITLE
Насадка для рыбной ловли

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#344]
в общем, вот чо в оригинале:
"Use: When applied to your fishing pole, increases Fishing by 100 for 5 minutes."
и переводится это прмиерно так:
"При применении на удочку повышает ваш навык рыбной ловли на 100 в течение 5 мин."
какой еще крючок наши выдумали? не знаю, может каких-нибдь ньюби это в ступор введет, так что лучше исправьте.
![wow 2017-08-10 21-54-55-265](https://user-images.githubusercontent.com/29949340/29215051-8cece434-7eba-11e7-91a5-843c4726ad75.jpg)

зачекайте все насадки

**Comment by Artur91425** [comment]
Ну приманка ведь на крючок насаживается) Не всегда стоит дословно переводить, главное передать правильный смысл.
