### ISSUE TITLE
Проблемы с названием спеллов

### ISSUE THREAD

**Issue by Artur91425** [WoWruRU/classicdb_ruRU#349]
Перенес в отдельный репорт.

**FTNonsense** commented 5 hours ago:
и еще вот здесь, не знаю баг ли это, поэтому сюда напишу.
когда изучаешь "первую помощь" на умельца, то книга зовется "умелец первой помощи", но заклинание изучения почему-то переводится как "Первая помощь (умелец)". Может заменить на "Умелец первой помощи"?
![wow 2017-08-10 22-07-17-539](https://user-images.githubusercontent.com/29949340/29215487-353a27b8-7ebc-11e7-8b78-6f5d5e6aef58.jpg)

то же и с кулинарией
![wow 2017-08-10 23-00-10-156](https://user-images.githubusercontent.com/29949340/29223386-6e764456-7ed7-11e7-8787-887633b2b866.jpg)

**Comment by Artur91425** [comment]
Мне кажется все нормально.
Это скил учится по книге "Умелец первой помощи: снимая покровы" и название скила обучения (Первая помощь (умелец)" имеет тот же вид, что и другие заклинания обучения у тренера. Там такая же структура.

**Comment by FTNonsense** [comment]
не соглашусь, у энчантеров название каста с названием формул совпадает 100%

**Comment by FTNonsense** [comment]
и рыбная ловля
![wow 2017-08-16 00-32-22-902](https://user-images.githubusercontent.com/29949340/29365344-b466b21a-82a7-11e7-92a3-3cde6c0f4f5a.jpg)

**Comment by FTNonsense** [comment]
и еще вот тут
![s](https://user-images.githubusercontent.com/29949340/29518697-736c51c4-868b-11e7-9ea6-39aca5bddeaa.jpg)
![ss](https://user-images.githubusercontent.com/29949340/29518698-7390e750-868b-11e7-91fb-3285ef8fdb20.jpg)

**Comment by M2us** [comment]
Почему совпадают эти способности, Наложение чар и Жертвоприношение? Потому что на англ. там более ничего нет, просто название скила соот. и на русском также, название скила. А вот первая помощь, рыбная ловля и т.п., там указан ранг, Apprentice, Journeyman... вот собственно на ру. с древних времен была такая структура: Название скила (ранг). 

Поэтому, все правильно.
