### ISSUE TITLE
Далар Ткач Рассвета, безрассудство Аругала, текст задания

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#35]
Его? так ведь речь о книге! опечатка
![pds-pe20m18](https://user-images.githubusercontent.com/29949340/27993753-f359da38-64c0-11e7-8065-ba9159b6f7e3.jpg)

**Comment by FTNonsense** [comment]
В конце не хватает точки + текст про слугу как-то.. Чекните оригинал, я конечно понимаю, что servant, но тут он обращается на "вы". вообще надо разобраться с Даларом, где-то он тыкает, а где-то выкает

**Comment by FTNonsense** [comment]
![wow 2017-07-09 18-26-21-164](https://user-images.githubusercontent.com/29949340/27994733-2965b60c-64d4-11e7-9077-2414d4151288.jpg)
тут уже на вы

**Comment by FTNonsense** [comment]
Да уж, с "ты" "вы" у него проблема.

**Comment by Artur91425** [comment]
Также добавлю, что отсутствует точка. "... поискать себе достойного слугу."

**Comment by M2us** [comment]
Нет, как раз в "Его" не опечатка. По английскому описанию, нам требуется принести заклинание, взятое из книг Аругала. Вот: I need to study the spell known as Remedy of Arugal.
Ему нужно внимательно изучить заклинание "Зелье Аругала".

И также здесь: Retrieve for me the spell labeled Remedy of Arugal from those books.
Он просит добыть из этих книг заклинание "Зелье Аругала".
