### ISSUE TITLE
Оглушительный визг

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#367]
поменять описание на **_"Невозможность произносить заклинания."_**
на офе фиксанули
![wow 2017-08-13 19-17-00-679](https://user-images.githubusercontent.com/29949340/29275389-0373709c-811c-11e7-860f-dd840155e961.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0039_loc_spell_deafening_screech.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
