### ISSUE TITLE
Анализ Далара, текст задания

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#37]
подвеску рунической надписи? там предмет по-другому называется, опять промт-перевод.
![xxs1079snae](https://user-images.githubusercontent.com/29949340/27993774-4b725b78-64c1-11e7-98c4-c7162b33f826.jpg)

**Comment by FTNonsense** [comment]
Подвеска с рунической надписью или как-то так.

**Comment by FTNonsense** [comment]
Исписанная рунами подвеска - во

**Comment by M2us** [comment]
[Исправлено.](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0030_dalar_dawnweaver_quests.sql#L18)
