### ISSUE TITLE
Чары для наручей - интеллект I

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#370]
почему "браслеты"? наручи же. Проверьте все чарки для наручей тогда, может там тоже эта ошибка.

![wow 2017-08-13 23-35-02-309](https://user-images.githubusercontent.com/29949340/29276293-2986a526-811f-11e7-817d-550bfa33ffb2.jpg)

**Comment by M2us** [comment]
[Изменения ](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0061_loc_spell_enchant.sql)будут приняты в следующем обновлении после 28.09.2017.
