### ISSUE TITLE
траченный навык: Огонь

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#374]
убрать слово "ед".
![wow 2017-08-14 21-12-19-111](https://user-images.githubusercontent.com/29949340/29315661-615235d6-81d5-11e7-9d5a-e2d47b4f71ae.jpg)
см.
https://github.com/WoWruRU/classicdb_ruRU/issues/318
https://github.com/WoWruRU/classicdb_ruRU/issues/319
https://github.com/WoWruRU/classicdb_ruRU/issues/320

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0036_loc_spell_forsaken_skill_shadow.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
