### ISSUE TITLE
Паразит

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#375]
не знаю, метель почему-то фиксанула описание, а вы говорили, надо обновляться вместе с ними.
поэтому описание дебаффа заменить на:
**_"45 ед. урона от сил природы раз в 10 сек."_**
![wow 2017-08-14 22-58-03-575](https://user-images.githubusercontent.com/29949340/29315744-d7265c38-81d5-11e7-8c47-c74ad2fa61b6.jpg)

**Comment by M2us** [comment]
Но, не всегда обновление идет в пользу. В данном случае из описания пропало слово inflicted. И не какой нибудь новичок может не понять, это он наносит столько урона или получает. Мое мнение такое, что нужно оставить слово "Получение".

45 Nature damage inflicted every 10 sec.

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0040_loc_spell_parasite.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
