### ISSUE TITLE
Изгнание

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#376]
судя по оригиналу:
Banishes the enemy target, preventing all action but making it invulnerable for up to 20 sec. Only one target can be banished at a time. Only works on Demons and Elementals.

первое предложение можно переделать проще и объемнее:
"Изгнание противника, предотвращающее всего его действия, но делающее его неуязвимым на 20 сек."
![wow 2017-08-15 00-59-52-074](https://user-images.githubusercontent.com/29949340/29316021-4c00c308-81d7-11e7-8574-fce4a6bbedcb.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0041_loc_spell_banish.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
