### ISSUE TITLE
Ядовитый выстрел

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#379]
метель опять фиксанула описание, так чтои  вам надо, наверное.
вот как должно быть:
"45 ед. урона от сил природы раз в 10 сек."
![wow 2017-08-15 18-16-08-524](https://user-images.githubusercontent.com/29949340/29337806-cef8c624-8223-11e7-9cb9-8c184d145c6c.jpg)

**Comment by M2us** [comment]
Но, не всегда обновление идет в пользу. В данном случае из описания пропало слово inflicted. И не какой нибудь новичок может не понять, это он наносит столько урона или получает. Мое мнение такое, что нужно оставить слово "Получение".

45 Nature damage inflicted every 10 sec.

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0042_loc_spell_poisoned_shot.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
