### ISSUE TITLE
Заказ Подрига, текст

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#38]
Очень много отступов, некорректно текст отображается, вылезает за рамки
![oyq09300ids](https://user-images.githubusercontent.com/29949340/27993794-9a25fab8-64c1-11e7-908c-277513ddd360.jpg)

**Comment by M2us** [comment]
Ошибка не является проблемой русификации игрового клиента или серверной локализации. Она связанна с использованием аддонов-переводчиков.
[Issue #16](https://github.com/WoWruRU/classicdb_ruRU/issues/16)
