### ISSUE TITLE
Дрожание земли -> "Земная дрожь"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#380]
ну, просто подумайте "earth tremor" - так ведь более по-русски звучит, чем дрожание земли..
и описание с "Оглушение" на "оглушен" поменять. где-то далеко сзади была тема, она уже просто переполнена подобными абилками.
![wow 2017-08-15 18-29-11-198](https://user-images.githubusercontent.com/29949340/29338276-8d6fd178-8225-11e7-8b5b-71d65242a1ec.jpg)

**Comment by FTNonsense** [comment]
заметьте, "mind tremor" перевели нормально здесь - https://github.com/WoWruRU/classicdb_ruRU/issues/381

**Comment by Artur91425** [comment]
а мне кажется вариант "Дрожь земли" лучше

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0043_loc_spell_ground_tremor.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
