### ISSUE TITLE
Мысленная дрожь

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#381]
метель сменила описание на 
**_"Скорость произнесения заклинаний снижена на 20%."_**
![wow 2017-08-15 19-06-56-630](https://user-images.githubusercontent.com/29949340/29338342-ce992b5e-8225-11e7-8ed6-d77964cc2d4d.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0016_loc_spell_mind_tremor.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
