### ISSUE TITLE
Грохот

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#382]
да-да, метель поменяла описание.
**_"Невозможность произносить заклинания."_**
![wow 2017-08-15 19-10-23-170](https://user-images.githubusercontent.com/29949340/29338425-36851b7e-8226-11e7-8f8e-64d038f5815c.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0017_loc_spell_sonic_burst.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
