### ISSUE TITLE
Проклятие крови

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#386]
исправить описание, даже метла его фкисанула, на:
**_"Получаемый физический урон увеличен на 17."_**
![wow 2017-08-15 19-37-46-334](https://user-images.githubusercontent.com/29949340/29339971-d5c07178-822d-11e7-88b6-d66bfb67301a.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/commit/fa163f80e936fdffaf448e682df9bfa226ffcc71) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
