### ISSUE TITLE
Проклятая кровь

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#387]
**_поменять описание дебаффа на "Интеллект снижен на 15." - убрать "ед" короче._** метель так уже сделала.
![wow 2017-08-15 19-47-17-119](https://user-images.githubusercontent.com/29949340/29340604-ed565340-8230-11e7-861d-65d0960559dd.jpg)

**Comment by Artur91425** [comment]
зачем убирать "ед."?

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0044_loc_spell_cursed_blood.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
