### ISSUE TITLE
Заклинания тьмы, описание предмета

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#39]
Очень сомнительный разлом четвертой стены с игроком. В оригинале совсем по-другому и другой смысл, настаиваю на исправлении
![gspdkbklm60](https://user-images.githubusercontent.com/29949340/27993809-c77f8c18-64c1-11e7-9074-9ed614030276.jpg)

**Comment by Furnicarium** [comment]
А как в оригинале и какой там смысл?
По мне и так очень достойно, почему бы не воспринимать это в прямом смысле или как шутку. В конце концов, в игре есть топор в форме огромного швейного лезвия, это ничего не ломает?

**Comment by FTNonsense** [comment]
"You know opening this would be a terrible idea."
"Вы понимаете, что открывать эту книгу - плохая идея"
Вот, пожалуйста.
