### ISSUE TITLE
Облучение

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#393]
поправить описание на вариант метлы
"5 to 10 ед. урона от сил природы раз в 3 сек. всем находящимся поблизости участникам группы."
![wow 2017-08-15 22-44-26-306](https://user-images.githubusercontent.com/29949340/29364108-805fc1f4-82a3-11e7-8729-7e2cc4ff046b.jpg)

**Comment by M2us** [comment]
Нельзя. )
Вот как на англ. сейчас (собственно предлагаемый вариант)
>5 to 10 Nature damage inflicted every 3 sec to nearby party members.

И как на классике.
>Emitting radiation.$BNature damage inflicted every $t1 sec.$BPeriodically inflicting Nature damage on nearby party members.

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0045_loc_spell_irradiated.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
