### ISSUE TITLE
Электрическая сеть

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#400]
в описании дебаффа стоит "immobilized" что переводится как "обездвижен", а не "обездвижевание".
![wow 2017-08-16 00-13-39-527](https://user-images.githubusercontent.com/29949340/29371018-33ce1862-82b8-11e7-8ed0-d2e36d1c35dd.jpg)

**Comment by M2us** [comment]
Все верно, "Обездвиживание."

Почему? Ответ здесь -> #281
