### ISSUE TITLE
Чары для плаща - защита и броня

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#405]
ну это лол вообще. "Броня" - это чарка на +10 и +20 брони, а защита на +30 и выше.
хотя в оригинале там все одинаково, только с приставкой "lesser" и так далее. Где-то уже был репорт.
ах, да - https://github.com/WoWruRU/classicdb_ruRU/issues/329
![wow 2017-08-16 00-53-27-485](https://user-images.githubusercontent.com/29949340/29377171-0679a2d2-82cc-11e7-924d-c6c99ef9dae9.jpg)

**Comment by M2us** [comment]
Все верно. Первые две называются Protection, а тот что на скрине - Defense. Но все они повышают броню (armor).
