### ISSUE TITLE
Далар Ткач рассвета, безрассудство Аругала, текст задания

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#41]
После запятой должен быть пробел.
![pbsdpznfi1a](https://user-images.githubusercontent.com/29949340/27993824-1da3f840-64c2-11e7-8c24-da53c6501df2.jpg)

**Comment by M2us** [comment]
[Исправлено.](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0030_dalar_dawnweaver_quests.sql#L14)
