### ISSUE TITLE
Притворная смерть

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#416]
не нашел этого заклинания в базе, но уверен, что описание и название там надо полностью переделать. даже если нет, то элементарно название способности в дебаффе и самом дебаффе рознится, посмотрите, а?
![wow 2017-08-17 00-58-03-887](https://user-images.githubusercontent.com/29949340/29423366-86c90106-838c-11e7-9192-0791919e4dfd.jpg)

**Comment by M2us** [comment]
Название спела:
Left for Dead
Притворная смерть

И вот то, что в описании.
Feigning death.
Ложная смерть.

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0049_loc_spell_left_for_dead.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
