### ISSUE TITLE
Ледяной выстрел

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#417]
опять не нашел по базе способности. Проврьте, у нее точно нет описаний? ну хоть типа "замедлен"...
![wow 2017-08-17 01-05-31-082](https://user-images.githubusercontent.com/29949340/29423451-d3c3faba-838c-11e7-9697-140d89c94014.jpg)

**Comment by M2us** [comment]
Да, там действительно нет описания. И даже до сих пор на офе.

http://ru.wowhead.com/spell=6984
