### ISSUE TITLE
Чарлга Остробок

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#418]
всее фразы кроме последней полностью совпадают с озвучкой
в последней звучит типо:
"Кто следующий?"
что делать? что за странный рассинхрон?
![wow 2017-08-17 01-08-55-586](https://user-images.githubusercontent.com/29949340/29424202-d76f0382-838f-11e7-8c3a-d079dad46058.jpg)

**Comment by Artur91425** [comment]
Все речи НПС это серверная локаль.
