### ISSUE TITLE
Пламенный страж из племени Галак

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#425]
короче перевод неправильный, без контекста.
вот там на скрине жаровню видите? это типо у них священный огонь и эти два НИПа - специально его охраняют.
значит, их перевод должен быть что-то типа:
"Страж огня из племени Галак" ну или страж жаровни, типа того.
![s](https://user-images.githubusercontent.com/29949340/29436094-19cf60a2-83bb-11e7-872f-90712fe9c03f.jpg)
![ss](https://user-images.githubusercontent.com/29949340/29436095-19d01376-83bb-11e7-8752-862420635ae1.jpg)

**Comment by Artur91425** [comment]
Страж пламени?)
