### ISSUE TITLE
Заварушка у ПЛаменеющего Клинка

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#43]
Есть под Оргриммаром организация орков, которая, судя по названиям НИПов, гордон азывает себя "Пламенеющий Клинок" и служит "СОвету Теней"  казалось бы, все просто. Однако дебильные локализаторы промта так не думают, намутив с переводом окончательно. Я, честно, не знаю, какой перевод верный, но что-то должно быть исправлено срочно, либо в названиях нипов, либо в текстах заданий и всякие упоминания о организации, ибо это уже походит на то, будто у них там не одна секта, а штук пять каких-то там клинков.
Вот упоминания об организации, что я успел заскринить:
Задание "Силы разрушения..."
![wow 2017-07-09 14-56-31-874](https://user-images.githubusercontent.com/29949340/27993908-647796a4-64c3-11e7-827c-e768bdcccfc2.jpg)
В разговоре с Ниру Огненным Клинком. Почитайте все его тексты, он в своих же текстах из-за переводчиков по-разному называет свою же организацию...
![kojpbfrqkbk](https://user-images.githubusercontent.com/29949340/27993877-e1b0323a-64c2-11e7-8de7-09839b006a4a.jpg)
В описании подземелья у хозяев таверн:
![1](https://user-images.githubusercontent.com/29949340/27993884-110a3b52-64c3-11e7-8f96-7c8c42d1cdc1.jpg)
В задании "Тайные враги" у Тралла снова Пылающий:
![ewtf32ayza0](https://user-images.githubusercontent.com/29949340/27993895-2fecc31e-64c3-11e7-976b-87fe6e82ec5e.jpg)
В этой же ветке заданий у Тралла:
![jl2z7pt5loy](https://user-images.githubusercontent.com/29949340/27993903-4a0b6796-64c3-11e7-830f-ad7b51ec1665.jpg)

**Comment by FTNonsense** [comment]
Кажется я понял: Пламенеющий клинок является придатком пылающего клинка. Однако, лучше вам это проверить, поэтому я просто покидаю скринов с упоминанием этхи организаций и буду ждать вердикта. =)
![wow 2017-07-09 19-19-54-677](https://user-images.githubusercontent.com/29949340/27996744-2fa6d2d2-64fa-11e7-9e9c-5e1dc4f619e6.jpg)
![wow 2017-07-09 19-35-22-295](https://user-images.githubusercontent.com/29949340/27996755-63198880-64fa-11e7-9ddb-8728d936274a.jpg)
Огненный клинок? Может пламенеющий? Они же марионетки. Короче, надо смотреть англ текст, у меня к нему доступа нет, все на вас.
![wow 2017-07-09 19-35-38-728](https://user-images.githubusercontent.com/29949340/27996762-7add8714-64fa-11e7-8633-6d357964702c.jpg)
![wow 2017-07-09 19-36-06-043](https://user-images.githubusercontent.com/29949340/27996768-95ba909a-64fa-11e7-90e9-2dd768dbd261.jpg)
Короче я понял путаницу. Пламенеющий клинок это переведен  неправильно, Вместо ппламенеющего надо другое слово, да и по словарю все верно, очень вольно перевели. Аж уж как пламенеющий клинок перевести - не знаю, но точно не огненный и не пламенеющий, ибо путаница и тупость.
![wow 2017-07-09 19-36-23-709](https://user-images.githubusercontent.com/29949340/27996775-ad4dcae2-64fa-11e7-82eb-6efb457374e0.jpg)
![wow 2017-07-09 19-39-23-366](https://user-images.githubusercontent.com/29949340/27996787-fd1cd342-64fa-11e7-868f-41f2ecbdaa51.jpg)
Да, все верно. ПЛаменеющий клинок - очередной тупой перевод
![wow 2017-07-09 21-29-17-462](https://user-images.githubusercontent.com/29949340/27996790-1aa555ce-64fb-11e7-9c69-4b076c51c874.jpg)
![wow 2017-07-09 21-54-45-320](https://user-images.githubusercontent.com/29949340/27996792-24f24802-64fb-11e7-9875-3db6cca1aff6.jpg)

**Comment by FTNonsense** [comment]
![wow 2017-07-09 21-57-05-997](https://user-images.githubusercontent.com/29949340/27996805-53580d58-64fb-11e7-942d-9cf987411633.jpg)
![wow 2017-07-09 21-57-37-795](https://user-images.githubusercontent.com/29949340/27996808-6094fb5c-64fb-11e7-98a4-28072c4aebd7.jpg)

**Comment by FTNonsense** [comment]
ТАК. Я Разоббрался. Совет Теней - глобальная организация, в этот совет входит Пылающий Клинок - всякие орки-чернокнижники, лидером которых является Ниру. ППламенеющий клинок - отдельная организация, который командует Жергон и Баззалан и которая обосновалась в огненной пропасти. Перевод Пылающего клинка спорен, но путаницы с названиями окончательно окочена. И да, Огненный Клинок - ошибка, не забудьте.

**Comment by M2us** [comment]
Об этих организациях.
http://rpwiki.ru/%D0%A1%D0%BE%D0%B2%D0%B5%D1%82_%D0%A2%D0%B5%D0%BD%D0%B5%D0%B9
Burning Blade - Пылающий Клинок - перевод верен, иначе не перевести.
Searing Blade - Пламенеющий Клинок - можно было бы и Опаляющий Клинок/Тлеющий Клинок. Хотя по сути, смысл один и тот же. Но, эти организации можно считать одним целым. Да, разные владельцы, но это организации одной структуры. И таким образом подчеркивается их конкретная связь. 

То есть, организации названы верно. Да и на различных вики все эти наименования. Только собьет с толку. ))))
