### ISSUE TITLE
Проклятие шипов

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#435]
немного переделать описание, как у метели.
"50%-я вероятность получить от 35 до 58 ед. урона при атаке."
![wow 2017-08-18 04-59-11-153](https://user-images.githubusercontent.com/29949340/29441914-98a27e86-83df-11e7-88ce-26cc6e6926d5.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0050_loc_spell_curse_of_thorns.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
