### ISSUE TITLE
Яркая блесна

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#445]
однако при использовании название способности совсем другое, см. скрин.
это к слову о https://github.com/WoWruRU/classicdb_ruRU/issues/349
![wow 2017-08-18 23-47-47-476](https://user-images.githubusercontent.com/29949340/29496075-50f9f164-85dc-11e7-9693-505fc4ab9023.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0051_loc_spell_bright_baubles.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
