### ISSUE TITLE
Порченая кровь

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#449]
тут немного неточное описание, я подправил. фиксаните у всех рангов.
"Taints the Felhunter's blood for 1 min. When the Felhunter is hit with a melee attack, the attacker will lose 17 melee attack power for 10 sec. Stacks up to 5 times on a single target."
**_"Порча крови охотника Скверны, которая продлится 1 мин. При нанесении охотнику урона в ближнем бою, атакующий потеряет 17  силы атаки ближнего боя на 10 сек. Эффект действует до 5 раз подряд на одну цель."_**
![wow 2017-08-21 00-02-02-803](https://user-images.githubusercontent.com/29949340/29518657-5046767a-868b-11e7-843e-cab4940e0751.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0052_loc_spell_tainted_blood.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
