### ISSUE TITLE
Проклятие стихий

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#450]
снова странное описание. вот, я пофиксил:
"Curses the target for 5 min, reducing Fire and Frost resistances by 45 and increasing Fire and Frost damage taken by 6%. Only one Curse per Warlock can be active on any one target."
**_"Проклятие цели на 5 мин., снижая ее сопротивление магии огня и льда на 45, а получаемый урон от заклинаний той же школы увеличивается на 6%. Каждый чернокнижник может наложить на каждую цель только одно проклятие."_**
![wow 2017-08-21 00-03-19-499](https://user-images.githubusercontent.com/29949340/29518828-035fa826-868c-11e7-88f4-92067e99b501.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0053_loc_spell_curse_of_the_elements.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
