### ISSUE TITLE
ВКР "Воробей" малого калибра

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#452]
суть в том, что "ИКР" - абберивиатура с английского, то есть она не была переведена с оригинала, а так и осталась. Возможно на русском это будет звучать по-другому, так что надо фиксануть.)
![wow 2017-08-21 20-13-28-689](https://user-images.githubusercontent.com/29949340/29540196-5d2926d2-86de-11e7-9a25-2f2133d1f7c4.jpg)

**Comment by Artur91425** [comment]
Я так и не нашел расшифровку BKP. Как я понял это просто название серии оружия.
