### ISSUE TITLE
Порабощение демона

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#453]
в дебаффе написано "enslaved" что значит "порабощен", а не "порабощение".
подобных репортов был не один десяток до этого.
![wow 2017-08-21 22-26-21-155](https://user-images.githubusercontent.com/29949340/29574301-2fcf560e-8772-11e7-8b39-fbeee5a2c5a9.jpg)

**Comment by M2us** [comment]
А если это суккуб - демон женского персонажа? Тогда должно быть "порабощена". Так что, порабощение - как описание эффекта норм. )

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0055_loc_spell_enslave_demon.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
