### ISSUE TITLE
Горный пехотинец Креммень

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#455]
ну, в оригинале там "flint" - то есть либо переводите "Кремень" с одной "м", либо просто как "Флинт"
ибо это ну.. как-то тупо
![wow 2017-08-21 23-50-57-485](https://user-images.githubusercontent.com/29949340/29575872-e05fde5e-8776-11e7-851d-60d4769962f5.jpg)

**Comment by Artur91425** [comment]
мне кажется лучше сделать Флинт
