### ISSUE TITLE
Аптекарь Ренферелл, звериные сердца

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#46]
Вот это предложение переведено совсем не правильно, не зря я его сразу приметил.
Вот как в оригинале:
There is a toxicity to them that should be deadly to the very wolves in which the hearts beat!
То, как перевели - бред
![wow 2017-07-09 17-34-20-522](https://user-images.githubusercontent.com/29949340/27995071-471ba436-64d9-11e7-8e32-e740b0a51998.jpg)

**Comment by M2us** [comment]
Также не верный перевод этой строки:
I kept a few samples of the hearts acquired.
"_Я сохранил несколько полученных препаратов._"

Ведь после идет строка:
Take them to my colleague, Apothecary Zinge. 
В которой просится отнести те сердца (а не препараты), которые он **приберег**. Часть пойдет на "яд" (По заданию, ранее, говорилось о том, что Сильвана требует чтобы он создал "крутой" яд), а вот эти несколько сердец он просит отнести коллеге.
