### ISSUE TITLE
Огр из клана раздробленного хреба

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#466]
во-первых, сам перевод:
"Raaar!!! Me smash $r!"
что по идее должно быть чем-то типо:
**_"Рррааар!!! Моя ломать нежить!"_** ну вы поняли.

**_и далее, видите эту $r?_**
в русском у нас
Рррааар! Моя убить $R!
**_и поэтому раса с большой буквы, хотя не должна._**
а может я ошибаюсь и регистр ничего не значит и так и должно быть, но если нет, то подобных скриптовых речей много и все надо фиксить
![wow 2017-08-23 21-18-24-777](https://user-images.githubusercontent.com/29949340/29641377-57c37ed0-8874-11e7-9d60-7ab335b495a0.jpg)

**Comment by Artur91425** [comment]
регистр не имеет значения. Все расы и классы и фракции в игре возвращаются с заглавных букв, кроме тех, где в тексте указаны конкретные и записаны со строчных букв.
