### ISSUE TITLE
Порабощенный элементаль

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#468]
не нашел этого текста в ваших документах, походу эмоции.
так или иначе, судя по переводу, они переведены криво.
проверьте перевод всех эмоций этих элементалей, очень похоже, что смысл в них утерян и не передает посыл оригинала.

а пока исправьте баг с одной из них:
вторая фраза, там ведь ошибки, вот как надо:
**_"теряет силу и словно скала рассыпается на куски."_**
![wow 2017-08-23 21-49-21-360](https://user-images.githubusercontent.com/29949340/29668753-56e8ab42-88f2-11e7-9d15-b50f350cceae.jpg)

**Comment by FTNonsense** [comment]
и во всех дебафчиках ошибка.
"урон"
![wow 2017-08-23 21-51-17-404](https://user-images.githubusercontent.com/29949340/29668806-85e58546-88f2-11e7-88f2-2e1b9b7e0b91.jpg)

**Comment by Artur91425** [comment]
Нашел 5 скилов с данной ошибкой. По поиску посмотри данное словосочетание.

**Comment by Artur91425** [comment]
и с магическим уроном тоже были подобные ошибки

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0056_loc_spell_cracking_stone.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
