### ISSUE TITLE
Жгучая боль

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#470]
Ну, тут надо "создает большой уровень угрозы" или типо того, а не "Обеспечивает".
![wow 2017-08-23 22-39-17-314](https://user-images.githubusercontent.com/29949340/29669936-22443466-88f6-11e7-9389-21a6ed81f409.jpg)

**Comment by M2us** [comment]
Было [исправлено ](https://github.com/M2us/WoWClassic_dbc/commit/ab35d8d8a75c9ce4fc3244d4f38bf2a3972a45dc)в обновлении от 28.09.2017
