### ISSUE TITLE
НИПы в усадьбе Дабири

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#474]
во-первых, по-моему работник - это неправильный перевод. К тому же, что они делают на ферме?
не суть, в оригинале там "Dabyrie Laborer" - не совсем работник.
![wow 2017-08-24 21-42-58-047](https://user-images.githubusercontent.com/29949340/29693118-ef016dae-8944-11e7-8f40-ed8981fd08e6.jpg)

далее.
не хватает "из"
![wow 2017-08-24 21-43-02-913](https://user-images.githubusercontent.com/29949340/29693127-fa7b2ed6-8944-11e7-8752-080a515b9d5e.jpg)

**Comment by Artur91425** [comment]
Должно быть "Чернорабочий ..."
