### ISSUE TITLE
Проклятье стихий

### ISSUE THREAD

**Issue by Artur91425** [WoWruRU/classicdb_ruRU#482]
1490, 11721, 11722
Нужно немного переделать первое предложение. Вот, что сеичас:
"Проклясть цель на $d., ослабив ее сопротивление огню и магии льда на $s1. Получаемый урон от заклинаний магии огня и льда увеличивается на $s2%."

У меня есть два варианта:
1) "Проклясть цель на $d., ослабив ее сопротивление магии огня и магии льда на $s1. Получаемый урон от заклинаний магии огня и льда увеличивается на $s2%."
2) "Проклясть цель на $d., ослабив ее сопротивление огню и льду на $s1. Получаемый урон от заклинаний магии огня и льда увеличивается на $s2%."

**Comment by M2us** [comment]
Первый вариант лучше. Но зачем 2 раза писать слово "магии". Можно просто: ослабив ее сопротивление магии огня и льда...

Точно также, как сделано во втором предложении.

**Comment by Artur91425** [comment]
ну да, так лучше. Ставь свой вариант.

**Comment by M2us** [comment]
Изменения [1](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0053_loc_spell_curse_of_the_elements.sql) и [2](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0054_loc_spell_curse_of_shadow.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
