### ISSUE TITLE
Устрашающий рев ->Деморализующий рев

### ISSUE THREAD

**Issue by Artur91425** [WoWruRU/classicdb_ruRU#484]
там их очень много, по поиску найди xD

**Comment by M2us** [comment]
Пффф... всего 15 записей Demoralizing Roar в названиях способностей. ) Только потом еще нужно будет в описаниях чекнуть)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0057_loc_spell_demoralizing_roar.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
