### ISSUE TITLE
"не более чем на"

### ISSUE THREAD

**Issue by Artur91425** [WoWruRU/classicdb_ruRU#485]
во всех бонусах к магии есть эти слова:
"Увеличение урона и целительного действия магических заклинаний и эффектов не более чем на 33 ед."
Ну вот что за бред? Как вообще понимать "не более чем на"? Такое словосочетание употребляется для  ограничения какого-либо диапазона. Вот если бы у нас повышалась магия рандомно, ДО указанного значения, тогда было бы все логично. Но ведь у нас повышается значение **НА** конкретно именно это число!
Предлагаю удалить слова "не более чем", то есть сделать вот так:
"Увеличение урона и целительного действия магических заклинаний и эффектов на 33 ед."

**Comment by M2us** [comment]
А разве оно не рандомно? Ну, спел фигачит 19 - 25 ед. урона. Одели эту шмотку и наш спел будет фигачит 19 - 58. Там как прокнет, не всегда идет фулл урон. Даже на англ. написано: by up to, что в переводе означает ДО. Если бы они хотели сказать что это фиксированное значение, они бы как всегда написали BY, но здесь использовали by up to. В противном случае, это может означат что на англ. здесь грубая ошибка, ведь они указали, если более раскрыто переводить: не более чем на...

То есть, еще разочек: они указали что значение повышается by up to (вплоть до), вместо by (на). Другого варианта здесь просто нет. Так что, не знаю, не знаю. Скорее всего так и есть, что у тебя не всегда именно на 33 ед. и будет фигачить спел. Скорее всего будет наносить урона больше, может, один удар на 25 ед., второй на 29, но он не нанесет больше чем 33 ед. Нужно будет взять шмотку и потестить, без нее и с ней. Если хоть раз урон не будет больше 33 ед. или сколько там на шмотке, даже на 1 ед. меньше, то уже нужно указывать что "не более чем на".

**Comment by Artur91425** [comment]
Опытным путем было установлено, что урон от спд увеличивается ДО указанного значения, а не как предполагалось его полное увеличение НА. Это связано с тем, что данное число проходит через формулу урона, обрабатывается через коэффициенты и на выходе получается реальное увеличение ДО указанного значения.
