### ISSUE TITLE
26122 spell.dbc

### ISSUE THREAD

**Issue by Artur91425** [WoWruRU/classicdb_ruRU#486]
Время наложения заклинания "Цепное исцеление" снижено на $/1000;S1 сек.

Должно быть "Время произнесения".

**Comment by M2us** [comment]
[Изменения ](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0063_loc_spell_casting_time_and_speed.sql#L97)будут приняты в следующем обновлении после 28.09.2017.
