### ISSUE TITLE
Роли Андреан, месть мужа

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#49]
Здесь явно пропущено слово "он"
![wow 2017-07-09 18-36-07-421](https://user-images.githubusercontent.com/29949340/27995122-10a2bcea-64da-11e7-8a08-df901e8faffb.jpg)

**Comment by Furnicarium** [comment]
а мне и без "он" очевидно, что это Валдред убил жену.

**Comment by Artur91425** [comment]
Мне кажется здесь не нужно "он". Речь идет о Валдреде и не нужно еще раз указывать на него, ведь это в одном предложении написано. Там же пишется, что вот Валдред был другом, а затем убил его жену.

**Comment by FTNonsense** [comment]
Но по правилам русского языка здесь должно быть "он" - это все же художественный текст. Иначе просто напросто это логическая ошибка. Потому что с точки зрения именно логической составляющий этот "убил" может быть кто угодно, абсолютно. Нет, "Он" - определенно нужно.

**Comment by M2us** [comment]
Может я дурак, или лыжа не едет, но я здесь вижу текст о том, что он был его другом, пока не сделал вот это. Именно конкретизация "was my wife's murderer".
