### ISSUE TITLE
Возможная ошибка в cmangos_ruRU_support.patch

### ISSUE THREAD

**Issue by biosfree** [WoWruRU/classicdb_ruRU#490]
Возможно пропущенные запятые в конце добавляемых строк патча:

в 230 строке ```+    "ruRU",```

и в 250 строке ```+    LOCALE_ruRU = 8,```

В оригинальных src/shared/Common.cpp и src/shared/Common.h после мексиканской локали стоит запятая.

Не могу называться знатоком С++. Да и вроде и так и так работает но как то сразу чувствуется нарушение систематики синтаксиса, только остается вопрос, ошибка у нас, у оригинала, или "пофиг".

Пожалуйста поправьте меня если я зря на это обращаю внимание.

**Comment by M2us** [comment]
Не, все нормально. :)
