### ISSUE TITLE
Замена baseEnglish на loc8

### ISSUE THREAD

**Issue by shikulja** [WoWruRU/classicdb_ruRU#491]
в mangosZero есть скрипты для замены loc0 на loc8 и сохранения loc0(для возврата)
https://github.com/MangosExtras/MangosZero_Localised
Очень удобно, чтобы не патчить сервер, а использовать готовую сборку, что для локальных тестов в игре, вполне годный вариант.
Прошу адаптировать скрипты для cmangos.
Это простой и актуальный способ, использовать русский, пока cmangos не добавит поддержку возможно в будующем.

**Comment by M2us** [comment]
Наша цель предоставить людям русскоязычный текст (локализацию игры), но не инструментарий.
