### ISSUE TITLE
НИПы, хозяины дирижаблей в Тирисфале

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#5]
На первом скрине хозяин дирижабля Дуротара, по крайней мере так было недавно, но теперь они оба почему-то хозяины Тернистой Долины. В общем, Маус, исправьте, я из-за этого перепутал дирижабли.))
![wow 2017-07-06 23-31-25-148](https://user-images.githubusercontent.com/29949340/27936283-06422738-62c1-11e7-9172-4428747efd8b.jpg)
![wow 2017-07-06 23-31-33-297](https://user-images.githubusercontent.com/29949340/27936282-0641c18a-62c1-11e7-8f23-f4421caefd8d.jpg)

**Comment by M2us** [comment]
Ошибка не является проблемой русификации игрового клиента или серверной локализации. Она связанна с использованием аддонов-переводчиков.
[Issue #16](https://github.com/WoWruRU/classicdb_ruRU/issues/16)
