### ISSUE TITLE
Рахауро, испытание силы врага

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#50]
Судя по английскому тексту, это - очередной тупой перевод, не имеющий смысла
ВОт оригинал:
How goes your search for the Chasm? And the troggs?
Тогда уж не в пропасти, а "как проходят поиски Огненной Пропасти? И троггов?, хотя я бы лучше сделал "Огненной ПРопасти и троггов"
![wow 2017-07-09 22-13-34-178](https://user-images.githubusercontent.com/29949340/27996841-250dab64-64fc-11e7-925b-ca7263f8820d.jpg)
 - звучит более по-русски, а вы же все же локализируете, а не дословно переводите.

**Comment by FTNonsense** [comment]
Суть в том, что оригинал подразумевал, что игрок не знает где инст и должен его найти.

**Comment by M2us** [comment]
Можно было бы сделать: Как проходят поиски Огненной пропасти? А троггов?

Но, без первого, не найти второго. А так получается, что мы могли не найти еще первого, то есть пропасть, но может, нашли второе. Тогда, будет этот вариант: "_Как проходят поиски Огненной пропасти и троггов?_". Он самый оптимальный.

**Comment by Artur91425** [comment]
Погодите, Огненная пропасть это не Chasm, а Ragefire Chasm. Думаю стоило оставить просто пропасть
