### ISSUE TITLE
Далар Ткач Рассвета, безрассудство Аругала

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#51]
Классика на ты/вы, совету просмотреть все его задания, всю цепочку, так как я довольно поздно заметил эту проблему.
![wow 2017-07-10 00-00-41-314](https://user-images.githubusercontent.com/29949340/27998597-d8121dd2-6522-11e7-94f5-d817b7dc479a.jpg)
![wow 2017-07-10 00-10-23-399](https://user-images.githubusercontent.com/29949340/27998598-d814a64c-6522-11e7-80a5-8f33601877e8.jpg)
А вот на этом скрине на лицо ошибки в русском языке, и, просмотрев английский вариант:
Most excellent.  The mine will provide superb resources for our forces as we spread throughout Silverpine and into Azeroth.
Я считаю, что эти слова лишние, я их подчекрнул. А вообще можно в целом перевести предложение по-другому, потому что оно не по-русски звучит. ЧТо-то типо "рудник обеспечит Отрекшихся омтенными ресурсами по мере нашего продвижения по Серебряному бору и Азероту"
![wow 2017-07-10 00-10-08-733](https://user-images.githubusercontent.com/29949340/27998619-079a3bca-6523-11e7-9f23-c174fe25c930.jpg)

**Comment by FTNonsense** [comment]
Опять, к слову о "ты" "вы"
![wow 2017-07-10 01-12-00-235](https://user-images.githubusercontent.com/29949340/27998886-f3ec5a64-6526-11e7-8dc1-82b5f25c6f38.jpg)

**Comment by FTNonsense** [comment]
Сюда же в копилку. Все равно не забудьте сами все его кв проверить, я много пропустил. "Смерть Аругалу!"
![wow 2017-07-10 10-17-26-729](https://user-images.githubusercontent.com/29949340/28009517-c7492546-656c-11e7-961b-24c2917db419.jpg)

**Comment by FTNonsense** [comment]
![wow 2017-07-12 06-16-28-288](https://user-images.githubusercontent.com/29949340/28101363-13ddbe5e-66d9-11e7-8029-7982564e1149.jpg)

**Comment by M2us** [comment]
https://user-images.githubusercontent.com/29949340/27998619-079a3bca-6523-11e7-9f23-c174fe25c930.jpg
Да, согласен, читается сложновато. 

Most excellent. The mine will provide superb resources for our forces as we spread throughout Silverpine and into Azeroth.

Но я даже не знаю, (по крайней мере в голову не приходит) как можно более правильно описать смысл текста, что данный рудник будет обеспечивать их силы ресурсами, пока они продвигаются по Серебреному и далее Азероту.

"**_Великолепно. По мере нашего продвижения по Серебряному бору и далее по Азероту, рудник будет обеспечивать наши силы отменными ресурсами._** "

**Comment by M2us** [comment]
[Правка для ты/вы](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0030_dalar_dawnweaver_quests.sql)
