### ISSUE TITLE
Страж смерти Фарлия, засада в деревне

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#52]
Посмотрите условия выполнения задания, там, кажется 
**Помогите ловчей смерти Фарлии уничтожить Совет деревни Погребальных Костров.**
**Помогите Фаэрлее уничтожить Совет деревни Погребальных Костров**
![wow 2017-07-10 00-29-04-539](https://user-images.githubusercontent.com/29949340/27998790-93676b76-6525-11e7-805a-28eb6b61cf9d.jpg)
То есть уже ошибка, не Фаэрлее

А вот здесь лишняя буква "в" и какой-то странный перевод. Что еще за вящей? В общем, перевод тупой, тут скорее "для Леди Сильваны" или "для" - что-то такое
![wow 2017-07-10 00-27-33-261](https://user-images.githubusercontent.com/29949340/27998778-810de3ba-6525-11e7-85bc-2a3576d19ebd.jpg)
Затем снова классическое "ты" "вы", ну и дебильный перевод предложения. Какое еще "честь имею"? Что еще за построение такое: "раз и навсегда и выбить" - не по-русски, на уровне пятиклассника.
Да и смотрите оригинал:
You fought like a true disciple of the Dark Lady, <name>.  With the council dead, perhaps we can gain control of this town once and for all and drive Arugal from Shadowfang Keep.  I salute you!
Короче "честь имею" как минимум надо убрать или перевести номрально
![wow 2017-07-10 00-29-31-472](https://user-images.githubusercontent.com/29949340/27998802-e6499fd0-6525-11e7-8af4-719c8e1616f3.jpg)

**Comment by M2us** [comment]
_Что еще за построение такое: "раз и навсегда и выбить" - не по-русски, на уровне пятиклассника.
Да и смотрите оригинал:
You fought like a true disciple of the Dark Lady, $N. With the council dead, perhaps we can gain control of this town once and for all and drive Arugal from Shadowfang Keep. I salute you!_

Так-то, переведено верно, но это близстоящее и, и - не корректно. Правильнее будет вот так: 
"_Вы сражались как истинный последователь Темной Госпожи, $N. Теперь, когда члены Совета мертвы, может быть, мы сможем раз и навсегда восстановить контроль над этой деревней и выбить Аругала из крепости Темного Клыка._"

А салют, пожалуй просто опустим. Все возможные варианты совсем не подходят под общую тематику.
