### ISSUE TITLE
Пыльные заклинательные книги

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#55]
Ну, это странно конечно ведь Old Spelbooks - старые книги заклинаний, ну, ладно, пыльные книги заклинаний.

**Comment by M2us** [comment]
Если что, там Dusty Spellbooks.
Ну и конечно, правильно будет назвать **Пыльные книги заклинаний**

![15108](https://user-images.githubusercontent.com/17622429/29323666-4413e680-81ea-11e7-9f95-01d3e3f3f998.jpg)
