### ISSUE TITLE
Сглаз Когтеврана-"Когтя ВОрона"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#57]
Это тупой перевод, жесть. ravencrow с англ и есть тот самый коготь ворона, просто переводчики скилла не посмотрели на имя персонажа и вообще.. тупые, короче. Такое уже видел у зомби
В общем, бутылка должна снимать "Сглаз Когтя Ворона" - злодея Зовут тул Коготь Ворона, логично, да?
ПОэтому и скилл ему переименуйте, ибо он тоже назван "сглаз когтеврана" - подобный баг встречался, только со скиллом зомби. Да и метку под скилыл отдельную бы надо.
![wow 2017-07-10 09-30-49-125](https://user-images.githubusercontent.com/29949340/28009293-eed88238-656b-11e7-8b14-84ca3f08299d.jpg)
Не забудьте про способность самого Тула

**Comment by FTNonsense** [comment]
![dfdf](https://user-images.githubusercontent.com/29949340/28022475-5a00b618-659c-11e7-8640-f1f13ec31236.jpg)
![sdds](https://user-images.githubusercontent.com/29949340/28022476-5a06c788-659c-11e7-8762-7d5d2591596d.jpg)
Доказательства, что рэйвенклоу - это и есть коготь ворона и все логично, просто переводчики дураки

**Comment by M2us** [comment]
Изменения [1](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0001_loc_spell_ravenclaw.sql) и [2](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0003_loc_spell_ravenclaw.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
