### ISSUE TITLE
Темный жрец Алистер, погибель Берена

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#58]
Очередной дебильный перевод. Просто сравните с оригиналом:
Have you located their base yet, <name>? Time is of the essence!
Надо менять
![wow 2017-07-10 10-16-46-065](https://user-images.githubusercontent.com/29949340/28009446-86f4097a-656c-11e7-88be-7b2b6e6ada12.jpg)

**Comment by M2us** [comment]
[Исправлено](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0056_quest_beren's_peril.sql).
