### ISSUE TITLE
Бесславная цель-"Беззащитная цель"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#59]
в скобках правильный вариант. Очередной тупой перевод способности, которая вешается игрока при перехода на лкоацию, мол, после загрузки за убийство этого игрока убийца не получит очков чести. Перевели это... дебильно, корректнее будет вот так:
**Беззащитная цель**
_За победу над вами противник не заслужит чести.
Осталось: 30 секунды_
![wow 2017-07-10 11-18-54-343](https://user-images.githubusercontent.com/29949340/28009842-facee2f6-656d-11e7-8bd6-03f47117e684.jpg)

**Comment by Furnicarium** [comment]
Не надо говорить, что по-дебильному. "Honorless Target" в оригинале. Хонор - честь, слава. За убийство игрока с таким баффом, убийце не дадут хонора, всё норм. Бесславная цель это очень удачный как буквально, так и по смыслу перевод.

**Comment by FTNonsense** [comment]
Ага, именно поэтому близзард на офе сменили на мой вариант, да? не, я бы не стал репортить это, если бы не официальный фикс.

**Comment by Furnicarium** [comment]
на офе много чего упростили в угоду малообразованным людям. игрок с таким дебаффом вовсе не обязательно беззащитен, я могу выйти из данжа и ох как защитить себя. но если меня убьют, хонора никто не получит, так что близы ошиблись.

**Comment by M2us** [comment]
Здесь действительно ошибка. Игрок выходит из подземелья и получает данный эффект. Прочитав его "**Вы не заслуживаете ни капли чести от противника.**", можно понять что мы не заслужим чести от противника. Даже возникает вопрос: то есть, убив его, я не получу очков чести? Но ведь именно противник не получит чести, убив нас.

Но в ЛК это исправили, переведя как: "**За победу над вами противник не заслужит чести.**". Данное описание даже разбирать для его понимания не нужно.

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0004_loc_spell_honorless_target.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
