### ISSUE TITLE
Дистанционно-управляемый гоблин

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#61]
В имени явно не хватает дефиса, даже в английском варианте он есть
![fg](https://user-images.githubusercontent.com/29949340/28010102-dadb0672-656e-11e7-8ad4-1b464610a0da.jpg)

**Comment by Furnicarium** [comment]
тут всё правильно. Дефис не всегда переносится из языка в язык, изучите тему "дефис в английском".
Сравните "Kind-hearted friend (мягкосердечный человек)" или "Ninety-seven (девяносто семь)"

**Comment by M2us** [comment]
Все верно. Он не всегда переносится. Плюс, в русском языке, слово "Дистанционно управляемый" пишется БЕЗ дефиса.
