### ISSUE TITLE
Гоблин-корабел - Гоблин-кораблестроитель

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#62]
В оригинале это shipbuilder и я думаю, что самым корректным будетн азвать гоблина именно кораблестроителем.
![wow 2017-07-10 11-59-57-302](https://user-images.githubusercontent.com/29949340/28010422-f045c258-656f-11e7-8740-3c092d462d6e.jpg)

**Comment by Furnicarium** [comment]
Корабел - это грамотное русское профессиональное слово. а "кораблестроитель" - разговорное, простонародное с тем же значением. не надо ничего менять.

**Comment by FTNonsense** [comment]
Что-то не вижу, чтобы в английском тоже использовали какие-то профессиональные термины, чтобы подбирать в русском схожий аналог. Вообще, подобные слвоа не всегда очевидны, а варкрафт является продуктом именно массовой культуры, поэтому разговорное слово здесь куда кстати.

**Comment by M2us** [comment]
Во-первых, нет разницы, корабел или кораблестроитель. Верно будет так, и так. Главное передать смысл.
Во-вторых, данный перевод был сделан в угоду тех. стороне, чтобы встречалось меньше НПС, чьи имена уходя внутрь окна и не отображаются полностью.

Итог: перевод верный.
