### ISSUE TITLE
Бетор Ледостер, "ты" "вы"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#63]
На сколько я помню, то он регулярно меняет свое отношение к игроку. Проверьте пожалуйста все задания у него, что-то я такое помню, но не придал внимания.
![wow 2017-07-10 09-25-21-676](https://user-images.githubusercontent.com/29949340/28010629-93bee630-6570-11e7-8fa2-8af50c8cf676.jpg)

**Comment by Furnicarium** [comment]
ну да, и если Ваш, то с большой буквы

**Comment by M2us** [comment]
Чаще всего он обращается к игрокам на ВЫ, соот. будет везде изменено на вежливое обращение.

Что касаемо Вы, то в игре не используется такой верблюжий стиль. Такой же случай, как и с буквой Ё. Так уж повелось. )
