### ISSUE TITLE
Замаскированный тайник

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#64]
Аларик тоже не может определиться, на "ты" или на "вы" он обращается к игроку
![wow 2017-07-10 13-29-36-368](https://user-images.githubusercontent.com/29949340/28022354-f9146a8e-659b-11e7-9360-fffb296213b2.jpg)
![wow 2017-07-10 13-33-48-036](https://user-images.githubusercontent.com/29949340/28022352-f8444bec-659b-11e7-84e3-9bdc795fd288.jpg)
![wow 2017-07-10 13-33-53-535](https://user-images.githubusercontent.com/29949340/28022351-f838e374-659b-11e7-8ed5-d766f61ef23f.jpg)

**Comment by FTNonsense** [comment]
А вот здесь по-русски будет "презирал ее", нежели "презрел"
ну и классика "ты" "вы"
![wow 2017-07-10 13-34-11-867](https://user-images.githubusercontent.com/29949340/28022404-257ca9b0-659c-11e7-9218-662400bf2412.jpg)

**Comment by M2us** [comment]
В основном обращается на ты. Да и какое уважение от "духа"?)

Что касаемо слова "**презрел**"

Настоящее время. Прошедшее время. Будущее время. Повелительное наклонение. 
Я  презрел; презрела; презрело презрю  
Ты  презрел; презрела; презрело презришь презри 
Он/она  презрел; презрела; презрело презрит  
Мы  презрели презрим презрим; презримте 
Вы  презрели презрите презрите 
Они  презрели презрят

написано правильно, такое слово есть. Презрел ее, он презрел - в прошедшем времени, когда то и по-нынешнее.

http://www.morfologija.ru/%D1%81%D0%BB%D0%BE%D0%B2%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%B0/%D0%BF%D1%80%D0%B5%D0%B7%D1%80%D0%B5%D0%BB
