### ISSUE TITLE
Заствший оазис, посадить семена

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#67]
Как можно посадить семена в расселину, которые бесплодны, еще и под водой? Здесь скорее может положить семена, поставить там, не знаю.
![wow 2017-07-10 19-17-11-443](https://user-images.githubusercontent.com/29949340/28067908-47c93822-6654-11e7-9468-a94242145948.jpg)

**Comment by M2us** [comment]
Переведено все верно. Почему? Вот собственно англ. текст. Посадить семена...
Plant Seeds - Plant these seeds in the Stagnant Oasis fissure.

А вот вырезка из задания "_Я дал тебе иссохшие, мертвые семена._" ... "_создает жизнь из ничего_". Мы посадили мертвые семена, но они проросли. То есть, мы посадили их в расселину. Говорят так, когда обращаются с семенами, их не кладут, их садят.
