### ISSUE TITLE
Налпак, шкуры загадочных сущесьв

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#68]
Вот в оригинале есть интересное предложение
While evil in nature, it is my opinion that some good can come from their existence here in Kalimdor. 
Я бы перевел как "в то время как зло является их природой, я уверен, что и из их существования можно извлечь что-то хорошее.
Тут просто в англ как бы игра слов evil and good, а не чистая коммерция, как представлен таурен в русском варианте. Ну и.. запятой нехватает "здесь, в Калимдоре"
![wow 2017-07-10 19-24-54-267](https://user-images.githubusercontent.com/29949340/28068206-814819f0-6655-11e7-98bf-86312b8ce1e7.jpg)

**Comment by M2us** [comment]
Ну да, While evil in nature можно перевести как - В то время как зло является их истинной природой...

А что касаемо этой стройки: it is my opinion that some good can come from their existence here in Kalimdor.
То здесь правильнее будет написать: я уверен, что их существование может принести некоторую пользу...

Потому что именно так говорится в англ. тексте, что они могут принести некоторую пользу. Извлечь, принести, особой роли не играет, но так будет правильнее. Приближенно к оригиналу.
