### ISSUE TITLE
Я даже не нашел правильного названия, пусть будет яд

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#74]
В инетрнете я не нашел ка кэто называется в оригинале, но русский вариант - это полная тупость, я даже смею предположить, что нормальный перевод этого будет что-то "Слабый яд" или как-то так.
В общем, надо исправить эту тупость
![wow 2017-07-10 21-07-48-677](https://user-images.githubusercontent.com/29949340/28069627-2c014f06-665b-11e7-99e8-b5aea92dd810.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0005_loc_spell_localized_toxin.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
