### ISSUE TITLE
Лорд Кобран, фраза

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#75]
В озвучке он говорит "спящего", да и действительно, Наралекс впал в Изумрудный сон. Разница между дремать и спать колоссальная, правильным будем "спящего", в изумрудном сне не дремлют.
![wow 2017-07-10 21-24-00-611](https://user-images.githubusercontent.com/29949340/28069750-a15648b0-665b-11e7-98e8-ecb473b8b3e7.jpg)

**Comment by Artur91425** [comment]
да и с маленькой буквы думаю надо

**Comment by FTNonsense** [comment]
Кстати, как во время дремоты можно видеть сны и кошмары? во время защиты Наралекса и его ученика говорится, что он видит кошмар.
И да, тут название локации надо переименовать в Утес Спящего тоже.
![wow 2017-07-11 22-29-04-401](https://user-images.githubusercontent.com/29949340/28089351-d0fae7d6-6699-11e7-882b-2d85bbdfa7d6.jpg)

**Comment by M2us** [comment]
Дело в том, что здесь написано dreamer, что более правильно как Дремлющий. Да и предметы, понятия в которых фигурирует слово dreamer, переведены как Дремлющий. Наплечные пластины Дремлющего и т.п. Даже в стратегии Варкрафт 3, нас просят разбудить дремлющих друидов, подув в рог, потому что те, кто впал в спячку, их стали называть как Дремлющие. В игре есть понятие как Sleep, так и Dreamer. Собственно, даже по лору, их ранее нарекли как Дремлющие. Так что, ошибка скорее в озвучке.

Во многих других играх нас также просят пробраться в гору и освободить, подчинить дремлющего дракона и т.п. 

Было бы правильнее исправить озвучку, но, не думаю, что нам удастся связаться с актером и попросить его переозвучит этот диалог. Да и если все же перевести, так сказать, подогнать под озвучку, то слишком много написано историй, в которых фигурирует именно как понятие - Дремлющий. Переименование разрушит общий, написанный лор как самими авторами, так и различные фанатские истории. Да и я сам более склонен к переводу Дремлющие.
