### ISSUE TITLE
Котел

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#76]
Навел мышкой на этот вот котел в Пещере СТенаний, но перевод мне выдает "костер". Првоерьте, так как это я сам точно проверить не могу.
![wow 2017-07-10 22-04-05-420](https://user-images.githubusercontent.com/29949340/28069798-cd6c65b0-665b-11e7-9bff-52da20194e3e.jpg)

**Comment by Artur91425** [comment]
Вот он: 153576
Поправь перевод на "Котел"

**Comment by FTNonsense** [comment]
Большое спасибо, Lichery.)
Далее локация - Бастион. Та же проблема
![wow 2017-07-11 19-27-01-305](https://user-images.githubusercontent.com/29949340/28087441-855017bc-6693-11e7-95b5-50919f0230db.jpg)
