### ISSUE TITLE
Воющая субстанция

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#77]
Очень большой вопрос по переводу этого предмета
В оригинале как бы Wailing Essence, что, получается Стенающая субстанция, но я бы просто перевел как какая-то другая, но точно не "воющая" - это акт надругательства над русским языком
![wow 2017-07-10 22-44-54-132](https://user-images.githubusercontent.com/29949340/28070071-c51b7f58-665c-11e7-928a-ec4c2a47164d.jpg)

**Comment by FTNonsense** [comment]
![wow 2017-07-11 19-58-37-821](https://user-images.githubusercontent.com/29949340/28088233-19f9726c-6696-11e7-8bb8-524bd1d6884e.jpg)
к слову где еще упоминается, чтобы менять

**Comment by FTNonsense** [comment]
![wow 2017-08-02 10-59-16-294](https://user-images.githubusercontent.com/29949340/28925120-fd8ed5d6-7874-11e7-8a84-ee9b4c8a79dc.jpg)
еще на испарвление

**Comment by M2us** [comment]
Посоветовавшись, мы пришли к выводу, что все же правильно переведено. Здесь имеется ввиду что субстанция такая, как желе, издает какой-то пронизывающий звук. Wailing это что-то такое, воющее, кричащее, издающее какой-то низкий звук. 

Собственно, воющая субстанция – более правильный перевод.
