### ISSUE TITLE
Зараженная рана

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#78]
Полученный? 0_0 понятно, что очередной дебильный перевод, здесь скорее получаемый.
![wow 2017-07-10 23-01-59-161](https://user-images.githubusercontent.com/29949340/28070171-0ba8467c-665d-11e7-8989-32f458b1fb30.jpg)

**Comment by FTNonsense** [comment]
тот же жанр
![wow 2017-07-17 00-10-04-112](https://user-images.githubusercontent.com/29949340/28251921-c48b20ee-6a98-11e7-9c94-cfb20f8f36c0.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0006_loc_spell_agonizing_pain.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
