### ISSUE TITLE
Прилив сил

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#79]
Даже не знаю английского текста, я на 100 процентов уверен, что этот тупой промт перевод неверный
![wow 2017-07-11 00-02-31-419](https://user-images.githubusercontent.com/29949340/28071266-7a30ad0c-6660-11e7-8908-c27a4a78aeb7.jpg)

**Comment by M2us** [comment]
Так-то, все верно переведено.

While channeling this spell, your mana regeneration is active and increased by 1500%.  Lasts 8 sec.

Поддерживая это заклинание, ваша регенерация маны активна и увеличена на 1500%. Время действия – 8 сек.

То есть, во время действия этого заклинания, наша регенерация маны активна (а в бою мана не регенится, но благодаря спелу, может) и мало того, еще и восстанавливается в 1500% быстрее.
