### ISSUE TITLE
Поиск ПВП

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#80]
Сменить подземелье? да неужели?) я себе Пвп искал.. Надо бы сменить, в классике поиска подезмелий не было.)
![wow 2017-07-11 00-06-07-710](https://user-images.githubusercontent.com/29949340/28071345-b60d6efa-6660-11e7-9e72-2a495e25e68e.jpg)

**Comment by M2us** [comment]
Change Instance.

И да, в классике был поиск игроков для подземелья. Мы становимся через инкипера или через камень призыва.
