### ISSUE TITLE
Эмиссар Осквернителей

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#81]
не смог найти англ текст, но русский вариант мне кажется каким-то нелогичным. Все, кроме первого предложения.
![wow 2017-07-11 00-06-12-042](https://user-images.githubusercontent.com/29949340/28071597-74137976-6661-11e7-939f-2cd4ddd1d85d.jpg)

**Comment by FTNonsense** [comment]
Дайте мне англ текст, и я напишу, что здесь не то. Я уверен, что что-то есть

**Comment by FTNonsense** [comment]
Our need for assistance in Arathi Basin is greater than one might imagine, $N.  So too is the honor and reputation one might acquire there in this time of need, however.  I implore you to seek out the Arathi Basin battlemaster in this city.			

вот. первое предложение мне нравится, но второе я бы поменял на:
**_"Но не меньше чести и репутации можно заслужить там в этот трудный час.	"_**

**Comment by M2us** [comment]
Так-то, там говорится что время сложное и т.п., но, благодаря этому "трудному времени", можно заслужить там честь и репутацию. Так что, и предлагаемый перевод тоже не особо верен. Словно нам изначально что-то предлагают, но и мол репу с честью тоже можно получить.
