### ISSUE TITLE
Лавка алхимика, Свиток заклятия проявления

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#83]
Для начало "проявления" должно быть с маленькой буквы, проверено. 
![wow 2017-07-11 00-16-01-597](https://user-images.githubusercontent.com/29949340/28072607-a123f5d2-6664-11e7-9ff9-6c2586b32a3e.jpg)
 Что у объекта, что у предмета.
![wow 2017-07-11 00-16-15-764](https://user-images.githubusercontent.com/29949340/28072637-b0869476-6664-11e7-9bd4-785acc782e6b.jpg)
затем тут явно тупой перевод "использовать возле возмущения Провала Маны", будто это какая-то определенная локация или НИП, еще и с больших букв, в то время как на англ
"Use near a mana rift disturbance" 
А тут явно тупой перевод, ведь судя по английскому здесь должен быть "создание шкатулки-духоловки из оглушенного..." **НЕТ. Судя по англ версии, здесь должно быть "СОЗДАНИЕ ДУХОЛОВКИ У ОГЛУШЕННОГО..."** ну переводчики и больные ублюдки были
Use: Create a containment coffer on a stunned Rift Spawn (8 Sec Cooldown)
![wow 2017-07-11 00-16-30-215](https://user-images.githubusercontent.com/29949340/28073006-9387a512-6665-11e7-81da-6b427c1d8876.jpg)
А вот тут все совсем печально, будто переводчик вообще понятия не имел, что переводит
Во-первых, Алжернон не алхимик, он все го лишь продает товары для Алхимии.  поэтому должно быть что-то "в алхимической лавке Алжернона"
затем, за спиной лежат не шкатулки-духоловки, и НЕ ящики, нет, а "chest" - шкатулки с духоловками. В корне неправильный перевод объекта, хотя не уверен, лучше еще проверьте, ну и собственно самого предмета с духоловками, который называется "ящик со шкатулками-духоловками", хотя должен быть "шкатулкой" с духоловками, короче эта два разных объекта, а тупой переводчик все напутал нахер, что у меня бомбит.  англ - "Chest of Containment Coffers"
еще, судя по англ версии, никакого подчинения нет, надо просто одолеть разлом, ну, или оглушить, короче сами решите. Да и не "В ЛАВКЕ", а скорее "рядом с лавкой" или как-то так.
Вот англ текст:
Algernon's alchemist shop in the Apothecarium is the locus of a strange disturbance. Invisible creatures, made solely of magic, wander the shop--there must be a reason, and we must find it!
_Investigate the disturbance and capture those creatures. Take a chest of coffers and a scroll from behind me. Use the scroll at the shop to make the creatures visible, subdue them with your spells, then throw down a coffer to capture them. Return with the filled coffers, the empty coffers and the cantation._
![wow 2017-07-11 00-24-29-981](https://user-images.githubusercontent.com/29949340/28073663-814db3a8-6667-11e7-8857-a569c559ad1e.jpg)
А тут... во-первых это Порождение разлома, а во-вторых это дерьмовый перевод самого заклинания,
![wow 2017-07-11 00-26-02-721](https://user-images.githubusercontent.com/29949340/28074039-9f9424ea-6668-11e7-8f50-eca7a206d112.jpg)
![wow 2017-07-11 00-29-51-842](https://user-images.githubusercontent.com/29949340/28074040-9fc919f2-6668-11e7-8120-caccd3a980fc.jpg)
а здесь куча опечаток: "и МЫ постараемся", а так же "их появлениЯ"
да и перевод сам незаконченный, тупой
_Very good, <name>. The creatures within these containment coffers will be studied by our finest minds, and the reason behind their presence in the Undercity will be determined.

If their appearance is caused by a rift in the natural flow of magic, then we must determine if the rift was random. If it was not random, but instead an attack by some magical force, then we must prepare for future, more serious disturbances._
судя поа нгл тексту тут тупо забыли перевести последнее предложение, просто проверьте.
![wow 2017-07-11 01-01-00-786](https://user-images.githubusercontent.com/29949340/28074354-6a2e7836-6669-11e7-93b7-8a28541a5e0b.jpg)

**Comment by FTNonsense** [comment]
Вот объектры, требующие исправления, недалеко от Анастасии Харвтелл.
Никаких ящиков со шкатулками-духоловками, это и есть шкатулки с духоловками, урод-переводчик
![vfd](https://user-images.githubusercontent.com/29949340/28074875-d18739a4-666a-11e7-8d0a-a53ab7f44d4c.jpg)

**Comment by M2us** [comment]
_>А тут... во-первых это Порождение разлома_
Не совсем ясно. Да, это порождение разлома. Перевод верен. Имя нпс не влазит во фрейм, такое бывает и на офе тоже.

_А тут явно тупой перевод, ведь судя по английскому здесь должен быть "создание шкатулки-духоловки из оглушенного..." НЕТ. Судя по англ версии, здесь должно быть "СОЗДАНИЕ ДУХОЛОВКИ У ОГЛУШЕННОГО..." ну переводчики и больные ублюдки были
Use: Create a containment coffer on a stunned Rift Spawn (8 Sec Cooldown)_


В плане шкатулки, все верно. Вот название предмета
Chest of Containment Coffers - Ящик со шкатулками-духоловками
То, что в описании - containment coffer. Ну да, нужно посмотреть, скорее не должно быть во множественном числе.
Ну и почему ИЗ, а не У. Потому что мы не саму по себе ее создаем. А мы ловим сущность разлома в нее. Соответственно, мы из него делаем ее, то есть, в итоге мы получаем из Разлома, заполненную шкатулку. Это ведь описание, а не лор. Что вот, из этого получится потом вот этот итем.
На русском именно так будет, и мало того, так более правильнее. Даже на англ. нет никаких "У", там также об этом говорится. 


_Вот объектры, требующие исправления, недалеко от Анастасии Харвтелл.
Никаких ящиков со шкатулками-духоловками, это и есть шкатулки с духоловками, урод-переводчик_

Хм. А вот здесь все сложно. Почему? Потому что объект называется, минуточку, Chest of Containment Coffers, что переводится как: Ящик со шкатулками-духоловками. И получаемый итем это тоже Chest of Containment Coffers.

Все же, говорить что это и есть шкатулка - в корне не верно.  Потому что мы этот ящичек открываем, и что достаем? Верно, мы достаем еще один ящик. http://www.wowhead.com/item=7247/chest-of-containment-coffers

Тут скорее вопрос уже к самим близам. Как это так, мы открываем объект: Chest of Containment Coffers и достаем с объекта, скажем так, еще один объект, то есть предмет, и это - Chest of Containment Coffers. 

Так что, попрошу без оскорблений, переводчик от близзов сделал все верно, он перевел. А то, что накосячили близы, это другой вопрос. Так что, исправлять в переводе здесь нечего.


Хм, ошибся, да. Все верно здесь. Потому что мы не достаем с него ящик и т.п.. Да, визуально достаем, но имеется ввиду, что мы просто берем этот ящичек в котором, минуточку, Containment Coffers - шкатулки-духоловки. Вот. И нет, снова таки, судя по английскому, это именно ящик со шкатулкой - Chest of Containment Coffers. 

И так. Объект: Chest of Containment Coffers - Ящик со шкатулками-духоловками - верно. Ящик в котором шкатулки духоловки. И мы этот ящик не открываем и ничего не достаем с него, а мы именно берем его, соот. этот объект попадает к нам в инвентарь. Название предмета такое же, Chest of Containment Coffers - Ящик со шкатулками-духоловками.
Со шкатулками вопрос закрыт.

_>Да и не "В ЛАВКЕ", а скорее "рядом с лавкой" или как-то так._
Так-то, везде и всегда на русском говорят: в лавке торговца. Ты найдешь ее в лавке торговца. Воспользуйся ею в лавке торговца. То есть, нам нужно подойти к ней. То что в игре, главное чтобы хитбокс спела хоть немного достал до лавки, это уже другой разговор. Но так-то, мы должны придти в лавку к торговцу.


_>с духоловками, короче эта два разных объекта, а тупой переводчик все напутал нахер, что у меня бомбит. англ - "Chest of Containment Coffers"_

А у меня уже от репорта. Если создается репорт, нужно хотя бы разобраться, что, как и почему. И разложить все по полочкам, а не так, что нужно еще пару часов убить на разбирательство и потом выяснить что половина из всего сделана правильно. Хоть бери и закрывай в будущем такие на коленке созданные репорты. Время просто вникуда.... спасибо автор тебе....


Изменения [1](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0008_loc_spellfocusobject_mana_rift_disturbance.sql) и [2](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0007_loc_spell_rift_spawn_becomes_visible.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
