### ISSUE TITLE
Скачок...

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#86]
В оригинале это выглядит как
**"Blink
Blinking"**
Я бы перевел как
**"Скачок
Перемещение."**
Нежели то, что сейчас, потому что прыжок со скоростью света как-то..  в стиле опечатки.
![wow 2017-07-11 19-12-45-148](https://user-images.githubusercontent.com/29949340/28087321-1ab5814e-6693-11e7-942e-053fc756d63e.jpg)

**Comment by M2us** [comment]
[Изменения](https://github.com/M2us/WoWClassic_dbc/blob/master/Updates/0009_loc_spell_blink.sql) будут приняты в новом игровом патче. Последняя версия игрового клиента на данный момент - 5.09.2016
