### ISSUE TITLE
Джозеф Грегориан, сбор материалов

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#89]
Здесь два варианта:
либо не хватает запятой, где я пометил и опечатка "для твоей одеяния"
**либо, к чему я более склоняюсь, здесь неправильный перевод.
смотрите англ текст:
Anastasia said you would come to me, and I am prepared to fashion your robes. Do you have the gems and the linen?
Да, тут коечно второй вариант, так как украсить робы готов сам Джозеф. "Я готов украсить твоюробу"**
![wow 2017-07-11 19-41-13-777](https://user-images.githubusercontent.com/29949340/28087980-62287408-6695-11e7-99db-1c49478448f6.jpg)
Да, тут второй вариант, надо нормально переводить.

**Comment by M2us** [comment]
На самом деле как-то странно на счет украшения. В самом начале говорится именно о создании одеяния. А тут, предлагаемый вариант, словно мы даем ему свою робу, а он ее с помощью этих материалов - украсит. 

Вот вырезка >Для создания нужного одеяния тебе понадобятся самоцветы маны 
Да и перед этим он сам говорит о создании одеяния. 

Так что, [закрыто](https://github.com/WoWruRU/classicdb_ruRU/commit/8f518d411cd56483224d5b8233fd26dc228304f9).
