### ISSUE TITLE
Свиток, покрытый письменами

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#9]
В свитке, дающемся всем магам нежити в начале игры как повод посещения учителя ошибки, какие-то буквы $G.
![wow 2017-07-08 00-36-56-803](https://user-images.githubusercontent.com/29949340/27981559-b3ce89ae-639e-11e7-8b2e-49711fa004d8.jpg)

**Comment by Artur91425** [comment]
Это текст 2447, вот тут вроде как вообще не тот перевод

**Comment by M2us** [comment]
Закрыто.
[0010](https://github.com/WoWruRU/classicdb_ruRU/blob/master/Updates/0010_page_text.sql)
