### ISSUE TITLE
Таланты

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#91]
Я никогда не задумывался об этом, но это ведь умения, а не таланты
и в оригинале это i want to reset my talents 
так выходит, что тогда должно быть
Я хочу разучить свои таланты
![wow 2017-07-11 20-08-57-871](https://user-images.githubusercontent.com/29949340/28088478-da43a498-6696-11e7-94c0-5242ce45e76a.jpg)

**Comment by M2us** [comment]
Да не, "умения" - норм. Потому что с талантами мы забываем и скилы. Во-первых, умения в таком случае более нейтральное. И во вторых, уже все привыкли к этому названию. И ничего в этом критичного нет.
