### ISSUE TITLE
Дворфийский костер

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#93]
В пещере стенаний? Проверьте-ка.
![wow 2017-07-11 21-55-04-473](https://user-images.githubusercontent.com/29949340/28088756-cbd54c08-6697-11e7-813b-c65c9795a703.jpg)

**Comment by Artur91425** [comment]
Это проблема аддона, для одного англ. варианта Campfire есть 4 варианта перевода
