### ISSUE TITLE
Морозный доспех

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#95]
Не совсем верный перевод
Помимо атаки еще скорость передвижения
Я бы перевел так
"Броня увеличена на 200. Замедляет скорость атаки и передвижения атакующих противников."
или что-то в этом роде
![wow 2017-07-11 22-12-14-953](https://user-images.githubusercontent.com/29949340/28089118-f17add6e-6698-11e7-95a8-4797157110b2.jpg)

**Comment by M2us** [comment]
Нет, все верно переведено. В данном отчете, попутано описание с другой способностью Морозный доспех, который используют НПС. Описание его эффекта звучит след.
Armor increased by 200.
Slowing melee attackers' movement and attacks.
Что собственно и было предложено.

А то, что в описании игрока, звучит след.
Increases Armor by 200 and may slow attackers.
