### ISSUE TITLE
Вердан Бессмертный - "Вердан Вечноживущий"

### ISSUE THREAD

**Issue by FTNonsense** [WoWruRU/classicdb_ruRU#96]
итак, immortal - бессмертный
everliving - вечноживущий
Даже локацию в честь этого босса перевели правильно - смотрите 1 скрин, а самого босса нет.
![wow 2017-07-11 22-16-56-689](https://user-images.githubusercontent.com/29949340/28089158-1fd2cd7a-6699-11e7-8084-95a14381e049.jpg)
![wow 2017-07-11 22-18-29-037](https://user-images.githubusercontent.com/29949340/28089169-293e4984-6699-11e7-8fd9-90ad434ec2b9.jpg)

**Comment by M2us** [comment]
На офе его имя сменили на Вердан Вечноживущий.
http://ru.wowhead.com/npc=5775
